openapi: 3.0.0
x-stoplight:
  id: 0f56e32f16f60
info:
  title: API Università
  x-summary: Questo servizio ritorna l'elenco dei corsi erogati da un un ifs.
  version: 1.0.0
  description: |
    ### Documentazione

    ## API Università
    La seguente documentazione API fornisce un riferimento per l'integrazione e l'accesso ai dati relativi alle università italiane. 
    Queste API consentono l'erogazione di servizi (e-service) che operano sui dati universitari, offrendo informazioni riguardanti le facoltà, i corsi di studio, i programmi accademici e altre informazioni correlate. 
    Questo sistema di integrazione permette di accedere ai dati in modo efficiente e aggiornato, facilitando lo sviluppo di applicazioni e servizi che riguardano il contesto universitario.

    # Corsi erogati da un IFS
    Questa API consente di ottenere l'elenco dei corsi erogati da un Istituto di Formazione Superiore (IFS). I dati restituiti includono informazioni sui singoli corsi offerti.

    **Endpoint:**   GET  /corsi

    **QueryParmas:**
      - courseType (opzionale): Tipologia del corso di studio (laurea, laurea magistrale, dottorato ricerca,ecc.). 
        Può essere utilizzato per ottenere solo i corsi di una determinata tipologia.
      - classCode (opzionale): Codice identificativo della classe di laurea. Può essere utilizzato per ottenere solo i corsi di 
        una specifica classe di laurea.

    **Esempio di risposta:**

    ```json
    {
      "instituteCode": "IFSRM1",
      "instituteName": "Università degli Studi di Roma 'La Sapienza'",
      "courses": [
        {
          "faculty": "Ingegneria",
          "courseType": "Corso di laurea",
          "courseName": "Ingegneria Informatica",
          "classCode": "L-8",
          "className": "Ingegneria dell'informazione"
        },
        {
          "faculty": "Ingegneria",
          "courseType": "Corso di laurea magistrale",
          "courseName": "Ingegneria Informatica",
          "classCode": "LM-32",
          "className": "Intelligenza artificiale"
        },
        {
          "faculty": "Economia",
          "courseType": "Corso di laurea",
          "courseName": "Economia e Commercio",
          "classCode": "L-18",
          "className": "Scienze Economiche"
        },
        {
          "faculty": "Giurisprudenza",
          "courseType": "Corso di laurea",
          "courseName": "Giurisprudenza",
          "classCode": "L-14",
          "className": "Scienze Giuridiche"
        }
      ]
    }

    # Verifica stato delle API (Health Check)
    Questa API fornisce un modo semplice per verificare lo stato di salute del sistema. 
    È un endpoint di base che può essere utilizzato per controllare se il servizio è in esecuzione correttamente.

    **Endpoint:**   GET  /status
  contact:
    name: helpdesk
    email: helpdesk@gmail.com
  x-api-id: 00000000-0000-0000-0000-000000000000
  termsOfService: 'http://swagger.io/terms/'
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
paths:
  /corsi:
    get:
      summary: Corsi erogati da un IFS
      tags:
        - CORSI-ISTITUTO
      parameters:
        - schema:
            type: string
          in: query
          name: courseType
          description: 'Tipologia del corso di studio (es. corso di laurea, corso di laurea magistrale, dottorato di ricerca…)'
        - schema:
            type: string
          in: query
          name: classCode
          description: Codice identificativo della classe di laurea
        - schema:
            type: string
          in: header
          name: Method
          description: Specifica il metodo HTTP utilizzato per la richiesta.
        - schema:
            type: string
          in: header
          name: Path
          description: Specifica il percorso o l'endpoint dell'API a cui viene indirizzata la richiesta.
        - schema:
            type: string
          in: header
          name: Scheme
          description: 'Specifica lo schema o il protocollo utilizzato per la comunicazione tra il client e il server, come HTTP o HTTPS.'
        - schema:
            type: string
          in: header
          name: Accept-Encoding
          description: 'Utilizzato per indicare al server le opzioni di compressione supportate dal client, come gzip o deflate.'
        - schema:
            type: string
          in: header
          name: Accept-Language
          description: 'Utilizzato per indicare al server la lingua preferita per la risposta, in modo che possa restituire la risposta nella lingua corretta, se disponibile.'
        - schema:
            type: string
          in: header
          name: Origin
          description: 'Utilizzato in contesti di sicurezza per indicare l''origine della richiesta, ad esempio durante le richieste CORS (Cross-Origin Resource Sharing).'
        - schema:
            type: string
          in: header
          name: User-Agent
          description: 'Utilizzato per identificare il client che sta effettuando la richiesta, ad esempio il browser e la versione utilizzata.'
      responses:
        '200':
          description: Richiesta eseguita con successo
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CorsiErogati'
              examples:
                Example 1:
                  value:
                    instituteCode: IFSRM1
                    instituteName: Università degli Studi di Roma 'La Sapienza'
                    courses:
                      - faculty: Ingegneria
                        courseType: Corso di laurea
                        courseName: Ingegneria Informatica
                        classCode: L-8
                        className: Ingegneria dell'informazione
                      - faculty: Ingegneria
                        courseType: Corso di laurea magistrale
                        courseName: Ingegneria Informatica
                        classCode: LM-32
                        className: Intelligenza artificiale
                      - faculty: Economia
                        courseType: Corso di laurea
                        courseName: Economia e Commercio
                        classCode: L-18
                        className: Scienze Economiche
                      - faculty: Giurisprudenza
                        courseType: Corso di laurea
                        courseName: Giurisprudenza
                        classCode: L-14
                        className: Scienze Giuridiche
          headers:
            Content-Length:
              schema:
                type: integer
                format: int64
              description: 'utilizzato per indicare la dimensione del corpo della risposta, consentendo al client di gestire correttamente la ricezione dei dati.'
            Cache-Control:
              schema:
                type: string
              description: 'utilizzato per indicare al client o ai server intermedi come gestire la memorizzazione nella cache della risposta, ad esempio "no-cache" per impedire la memorizzazione nella cache.'
            Access-Control-Allow-Origin:
              schema:
                type: string
              description: utilizzato per consentire a determinati origini di accedere alle risorse tramite richieste cross-origin.
            X-RateLimit-Limit:
              schema:
                type: integer
                format: int64
              description: specifica il numero massimo di richieste consentite entro un determinato periodo di tempo (solitamente misurato in secondi).
            X-RateLimit-Remaining:
              schema:
                type: integer
                format: int64
              description: utilizzato per indicare il numero di richieste API rimanenti all'interno del periodo di tempo specificato dal server.
            X-RateLimit-Reset:
              schema:
                type: string
                format: date-time
              description: utilizzato per indicare il momento in cui il limite delle richieste API verrà ripristinato.
        '500':
          description: Errore interno del server
          headers:
            Content-Length:
              schema:
                type: integer
                format: int64
              description: 'utilizzato per indicare la dimensione del corpo della risposta, consentendo al client di gestire correttamente la ricezione dei dati.'
            Cache-Control:
              schema:
                type: string
              description: 'utilizzato per indicare al client o ai server intermedi come gestire la memorizzazione nella cache della risposta, ad esempio "no-cache" per impedire la memorizzazione nella cache.'
            Access-Control-Allow-Origin:
              schema:
                type: string
              description: utilizzato per consentire a determinati origini di accedere alle risorse tramite richieste cross-origin.
            X-RateLimit-Limit:
              schema:
                type: integer
                format: int64
              description: specifica il numero massimo di richieste consentite entro un determinato periodo di tempo (solitamente misurato in secondi).
            X-RateLimit-Remaining:
              schema:
                type: integer
                format: int64
              description: utilizzato per indicare il numero di richieste API rimanenti all'interno del periodo di tempo specificato dal server.
            X-RateLimit-Reset:
              schema:
                type: string
                format: date-time
              description: utilizzato per indicare il momento in cui il limite delle richieste API verrà ripristinato.
      operationId: corsi-erogati
      description: 'Restituisce l''elenco di tutti i corsi erogati. Se valorizzati i QueryParams (courseType, classCode) la lista verrà filtrata in base a quei valori'
  /status:
    get:
      summary: Verifica stato delle API (Health Check)
      operationId: check-status
      description: Verificare lo stato di salute del sistema
      tags:
        - HEALTH-CHECK
      responses:
        '204':
          description: il servizio è in esecuzione correttamente.
        '500':
          description: il servizio non è in esecuzione.
components:
  schemas:
    CorsiErogati:
      type: object
      x-examples:
        Example 1:
          instituteCode: IFSRM1
          instituteName: Università degli Studi di Roma 'La Sapienza'
          courses:
            - faculty: Ingegneria
              courseType: Corso di laurea
              courseName: Ingegneria Informatica
              classCode: L-8
              className: Ingegneria dell'informazione
            - faculty: Ingegneria
              courseType: Corso di laurea magistrale
              courseName: Ingegneria Informatica
              classCode: LM-32
              className: Intelligenza artificiale
            - faculty: Economia
              courseType: Corso di laurea
              courseName: Economia e Commercio
              classCode: L-18
              className: Scienze Economiche
            - faculty: Giurisprudenza
              courseType: Corso di laurea
              courseName: Giurisprudenza
              classCode: L-14
              className: Scienze Giuridiche
      description: Corsi erogati in un IFS
      properties:
        instituteCode:
          type: string
          description: Codice identificativo dell’istituto
          readOnly: true
        instituteName:
          type: string
          description: Nome dell'istituto
          readOnly: true
        courses:
          type: array
          description: Elenco corsi erogati
          items:
            type: object
            properties:
              faculty:
                type: string
                description: Nome della facoltà
                readOnly: true
              courseType:
                type: string
                description: Tipo di corso di studio
                example: 'laurea, laurea magistrale, dottorato di ricerca, specializzazione, master, formazione professionale'
                readOnly: true
              courseName:
                type: string
                description: Denominazione del corso di studio
                example: 'ingegneria, economia, giurisprudenza, medicina, scienze umanistiche, scienze sociali, informatica, arte e design'
                readOnly: true
              classCode:
                type: string
                description: Codice della classe di studio
                pattern: '^[A-Za-z0-9-]+$'
                example: L-8
                readOnly: true
              className:
                type: string
                description: Denominazione della classe di studio
                example: 'Informatica, Meccanica, Elettronica, Civile'
                readOnly: true
  requestBodies: {}
  responses: {}
servers:
  - url: 'https://localhost:8080/api'
    description: localhost
tags:
  - name: API-UNIVERSITÀ
  - name: CORSI-ISTITUTO
  - name: HEALTH-CHECK
