openapi: 3.0.0
x-stoplight:
  id: 0f56e32f16f60
info:
  title: IFS06 - List of enrollment changes / Elenco variazioni iscrizioni
  x-summary: Acquires the list of students who have undergone a change of status at the relevant enrollment. / Acquisisce la lista delle studentesse e degli studenti che hanno subito un cambio di stato alla relativa iscrizione.
  version: 1.0.0
  description: |
    Obtains the list of students who have had variations in enrollment. / Ottiene l'elenco delle studentesse e degli studenti che hanno avuto variazioni alle iscrizioni.
  contact:
    name: helpdesk
    email: helpdesk@gmail.com
  x-api-id: 00000000-0000-0000-0000-000000000000
  termsOfService: 'http://swagger.io/terms/'
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
paths:
  '/enrollment-changes':
    parameters:
      - name: currentPage
        in: query
        required: true
        schema:
          type: integer
          format: int32
          description: Current page number / Numero di pagina corrente
          maximum: 9999
          minimum: 1
    get:
      summary: Enrollment changes / Variazioni iscrizioni
      tags:
        - enrollment changes
      security: [{}]
      responses:
        '200':
          description: Request successfully executed / Richiesta eseguita con successo
          content:
            application/json:
              schema:
                type: object
                additionalProperties: false
                x-examples:
                  Example 1:
                    items: 3
                    pages: 20
                    currentPage: 1
                    itemsPerPage: 15
                    instituteCode: 'C8'
                    lastUpd: '2023-09-21'                    
                    data:
                      enrollmentChanges:
                        - hash: 4ef246ed27b83886dd33377c0da06031 
                          taxCode: RSSMRA80A01H501B
                          personID: 1A3B5C7D9
                        - hash: 4ef246ed27b83886dd33377c0da06031
                          taxCode: BNCGLI85C44D612Y
                          personID: X5Y7Z9A2C
                        - hash: 4ef246ed27b83886dd33377c0da06031
                          taxCode: VRDLCA90H23E789Z
                          personID: M8N2P6QR4
                properties:
                  items:
                    type: integer
                    description: total available items / totale degli elementi disponibili
                    format: int32
                    readOnly: true
                    maximum: 256
                    minimum: 0
                  pages:
                    type: integer
                    description: total pages available / totale delle pagine disponibili
                    format: int32
                    readOnly: true
                    maximum: 256
                    minimum: 0                    
                  currentPage:
                    type: integer
                    description: number of the current page returned / numero della pagina corrente restituita
                    format: int32
                    readOnly: true
                    maximum: 256
                    minimum: 0                    
                  itemsPerPage:
                    type: integer
                    description: number of elements in the page / numero di elementi presenti nella pagina
                    format: int32
                    readOnly: true
                    maximum: 256
                    minimum: 0
                  instituteCode:
                    type: string
                    description: Institutional identification code / Codice identificativo dell’istituto  [** DA DEFINIRE PATTERN CORRETTO **]
                    example: 'C7'
                    readOnly: true
                    minLength: 2
                    maxLength: 2
                  lastUpd:
                    type: string
                    format: date
                    description: Date last updated / Data ultimo aggiornamento
                    example: '2023-10-13'
                    readOnly: true
                    pattern: '^\d{4}-\d{2}-\d{2}$'
                  data:
                    type: object
                    additionalProperties: false
                    description: actual data of the current page / dati effettivi della pagina corrente
                    maxItems: 256
                    minItems: 0
                    required:
                      - enrollmentChanges
                    properties:
                      enrollmentChanges:
                        type: array
                        description: List of students who had changes in enrollment / Elenco di studentesse e studenti che hanno avuto variazioni nelle iscrizioni
                        maxItems: 100
                        minItems: 0                        
                        items:
                          $ref: '#/components/schemas/Student'
                required:
                  - items
                  - pages
                  - currentPage
                  - itemsPerPage
                  - instituteCode
                  - lastUpd
                  - data
              examples:
                Example 1:
                  value:
                    items: 3
                    pages: 20
                    currentPage: 1
                    itemsPerPage: 15
                    instituteCode: 'C8'
                    lastUpd: '2023-09-21'
                    data:
                      enrollmentChanges:
                        - hash: 4ef246ed27b83886dd33377c0da06031
                          taxCode: RSSMRA80A01H501B
                          personID: 1A3B5C7D9
                        - hash: 4ef246ed27b83886dd33377c0da06031
                          taxCode: BNCGLI85C44D612Y
                          personID: X5Y7Z9A2C
                        - hash: 4ef246ed27b83886dd33377c0da06031
                          taxCode: VRDLCA90H23E789Z
                          personID: M8N2P6QR4
                Example 2:
                  value:
                    items: 0
                    pages: 20
                    currentPage: 1
                    itemsPerPage: 15
                    instituteCode: '19'
                    lastUpd: '2023-09-21'
                    data:
                      enrollmentChanges: []
        '400':
          description: One of the input fields appears to be missing / Risulta mancante uno dei campi di input                    
        '404':
          description: No changes were found in student enrollment / Non sono state trovate variazioni delle iscrizioni degli studenti
        '500':
          description: Internal server error / Errore interno del server
      operationId: enrollment-changes
      description: returns the list of students who have had enrollment changes. / restituisce l'elenco delle studentesse e degli studenti che hanno avuto variazioni alle iscrizioni.
      parameters: []
  /status:
    get:
      summary: Verifica stato delle API (Health Check)
      operationId: check-status
      description: Check the system's health status / Verificare lo stato di salute del sistema
      tags:
        - health-check
      security: [{}]
      responses:
        '204':
          description: The service is running correctly / Il servizio è in esecuzione correttamente
        '500':
          description: The service is not running / Il servizio non è in esecuzione
components:
  headers:
    Retry-After:
      description: |-
        Retry contacting the endpoint *at least* after seconds.
        See https://tools.ietf.org/html/rfc7231#section-7.1.3
      schema:
        format: int32
        maximum: 186400
        minimum: 0
        type: integer
    X-RateLimit-Limit:
      description: The number of allowed requests in the current period
      schema:
        format: int32
        maximum: 1000000
        minimum: 0
        type: integer
    X-RateLimit-Remaining:
      description: The number of remaining requests in the current period
      schema:
        format: int32
        maximum: 1000000
        minimum: 0
        type: integer
    X-RateLimit-Reset:
      description: The number of seconds left in the current period
      schema:
        format: int32
        maximum: 186400
        minimum: 0
        type: integer  
  schemas:
    Student:
      title: Student
      additionalProperties: false
      x-refersTo: https://w3id.org/italia/onto/CPV/Person
      x-jsonld-context:
        "@vocab": "https://w3id.org/italia/onto/CPV/"
        tax_code: taxCode
        personID: personID      
        hash:
          "@id": hash
          "@type": "@id"
          "@context":
            "@base": "https://w3id.org/italia/controlled-vocabulary/classifications-for-people/hash/" #[E' UN ESEMPIO]
      x-stoplight:
        id: h5iin6mdxsvx1
      type: object
      description: Identification data of a student / Dati identificativi di una studentessa o di uno studente
      x-examples:
        Example 1:
          hash: 4ef246ed27b83886dd33377c0da06031
          taxCode: RSSMRA80A01H501B
          personID: 1A3B5C7D9
      properties:
        hash:
          type: string
          description: Hash code / Codice hash
          readOnly: true
          minLength: 1
          maxLength: 32
          example : 4ef246ed27b83886dd33377c0da06031          
        taxCode:
          type: string
          description: Tax Identification Number / Codice Fiscale
          pattern: '^[A-Z]{6}\d{2}[A-Z]\d{2}[A-Z]\d{3}[A-Z]$'
          example: RSSMRA80A01H501B
          minLength: 16
          maxLength: 16
          readOnly: true
        personID:
          type: string
          description: ANPR Identifier / Identificativo ANPR 
          minLength: 9
          maxLength: 9
          pattern: '^[A-Z0-9]{9}$'
          readOnly: true
      required:
        - hash
        - taxCode
        - personID
  requestBodies: {}
  responses: {}
servers:
  - url: 'https://localhost:8080/api'
    description: localhost
tags:
  - name: enrollment changes
  - name: health-check
