openapi: 3.0.0
x-stoplight:
  id: 0f56e32f16f60
info:
  title: IFS06 - Elenco variazioni iscrizioni
  x-summary: Acquisisce la lista delle studentesse e degli studenti che hanno subito un cambio di stato alla relativa iscrizione tra un istante t0 e uno t1 compresi (ad es. t0 = 1 gennaio 2019 e t1 = 31 dicembre 2019 per richiedere i dati relativi all'anno solare 2019)
  version: 1.0.0
  description: |
    Ottiene l'elenco di codici fiscali delle studentesse e degli studenti che hanno avuto variazioni alle iscrizioni in un certo intervallo di tempo.
  contact:
    name: helpdesk
    email: helpdesk@gmail.com
  x-api-id: 00000000-0000-0000-0000-000000000000
  termsOfService: 'http://swagger.io/terms/'
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
paths:
  /variazioni-iscrizioni:
    get:
      summary: Variazioni iscrizioni
      tags:
        - variazioni iscrizioni
      responses:
        '200':
          description: Richiesta eseguita con successo
          content:
            application/json:
              schema:
                type: object
                x-examples:
                  Example 1:
                    totElem: 3
                    totPages: 1
                    currentPage: 1
                    perPage: 15
                    data:
                      students:
                        - fullName: Mario Rossi
                          taxCode: RSSMRA80A01H501B
                          personID: 1A3B5C7D9
                        - fullName: Giulia Bianchi
                          taxCode: BNCGLI85C44D612Y
                          personID: X5Y7Z9A2C
                        - fullName: Luca Verdi
                          taxCode: VRDLCA90H23E789Z
                          personID: M8N2P6QR4
                properties:
                  totElem:
                    type: integer
                    description: totale degli elementi disponibili
                    format: int32
                    readOnly: true
                  totPages:
                    type: integer
                    description: totale delle pagine disponibili
                    format: int32
                    readOnly: true
                  currentPage:
                    type: integer
                    description: numero della pagina corrente restituita
                    format: int32
                    readOnly: true
                  perPage:
                    type: integer
                    description: numero di elementi presenti nella pagina
                    format: int32
                    readOnly: true
                  data:
                    type: object
                    description: dati effettivi della pagina corrente
                    required:
                      - students
                    properties:
                      students:
                        type: array
                        description: Elenco di studentesse e studenti che hanno avuto variazioni nelle iscrizioni
                        items:
                          $ref: '#/components/schemas/Studente'
                required:
                  - totElem
                  - totPages
                  - currentPage
                  - perPage
                  - data
              examples:
                Example 1:
                  value:
                    totElem: 3
                    totPages: 1
                    currentPage: 1
                    perPage: 15
                    data:
                      students:
                        - fullName: Mario Rossi
                          taxCode: RSSMRA80A01H501B
                          personID: 1A3B5C7D9
                        - fullName: Giulia Bianchi
                          taxCode: BNCGLI85C44D612Y
                          personID: X5Y7Z9A2C
                        - fullName: Luca Verdi
                          taxCode: VRDLCA90H23E789Z
                          personID: M8N2P6QR4
                Example 2:
                  value:
                    totElem: 0
                    totPages: 1
                    currentPage: 1
                    perPage: 15
                    data:
                      students: []
        '500':
          description: Errore interno del server
      operationId: variazioni-iscrizioni
      description: restituisce l'elenco di codici fiscali delle studentesse e degli studenti che hanno avuto variazioni alle iscrizioni in un certo intervallo di tempo.
      parameters:
        - schema:
            type: string
            format: date
            example: '2022-04-10'
          in: query
          name: t0
          required: true
          description: data di inizio dell'intervallo da considerare
        - schema:
            type: string
            format: date
            example: '2023-07-06'
          in: query
          name: t1
          allowEmptyValue: true
          description: data di fine dell''intervallo da considerare (se non valorizzato vale la data del giorno)
        - schema:
            type: integer
            format: int32
            default: 1
            minimum: 1
          in: query
          name: page
          description: Numero della pagina che si vuole visualizzare
          required: true
        - schema:
            type: integer
            format: int32
            default: 15
            minimum: 1
          in: query
          name: limit
          description: Numero massimo di elementi per pagina
          required: true  
  /status:
    get:
      summary: Verifica stato delle API (Health Check)
      operationId: check-status
      description: Verificare lo stato di salute del sistema
      tags:
        - health-check
      responses:
        '204':
          description: il servizio è in esecuzione correttamente.
        '500':
          description: il servizio non è in esecuzione.
components:
  schemas:
    Studente:
      title: Studente
      x-stoplight:
        id: h5iin6mdxsvx1
      type: object
      description: Dati identificativi di una studentessa o di uno studente
      x-examples:
        Example 1:
          fullName: Mario Rossi
          taxCode: RSSMRA80A01H501B
          personID: 1A3B5C7D9
      properties:
        fullName:
          type: string
          description: Nome completo
          readOnly: true
        taxCode:
          type: string
          description: Codice fiscale
          pattern: '^[A-Z]{6}\d{2}[A-Z]\d{2}[A-Z]\d{3}[A-Z]$'
          example: RSSMRA80A01H501B
          minLength: 16
          maxLength: 16
          readOnly: true
        personID:
          type: string
          description: Identificativo ANPR
          minLength: 9
          maxLength: 9
          pattern: '^[A-Z0-9]{9}$'
          readOnly: true
      required:
        - fullName
        - taxCode
        - personID
  requestBodies: {}
  responses: {}
servers:
  - url: 'https://localhost:8080/api'
    description: localhost
tags:
  - name: variazioni iscrizioni
  - name: health-check
