openapi: 3.0.0
x-stoplight:
  id: 0f56e32f16f60
info:
  title: IFS03 - Recupero titoli
  x-summary: Questo servizio ritorna l'elenco dei titoli conseguiti da una studentessa o uno studente.
  version: 1.0.0
  description: |
    Restituisce l'elenco dei titoli conseguiti da una studentessa o uno studente
  contact:
    name: helpdesk
    email: helpdesk@mail.edu.it
  x-api-id: 00000000-0000-0000-0000-000000000000
  termsOfService: 'http://swagger.io/terms/'
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
paths:
  '/studenti/{taxCode}/titoli':
    parameters:
      - schema:
          type: string
          maxLength: 16
          minLength: 16
          pattern: "^([a-zA-Z]{6}[0-9L-Nl-nP-Vp-v]{2}[A-Ea-eHhLlMmPpRrSsTt][0-9L-Nl-nP-Vp-v]{2}[a-zA-Z][0-9L-Nl-nP-Vp-v]{3}[a-zA-Z])$"
        name: taxCode
        in: path
        required: true
        description: 'Codice Fiscale'
    get:
      summary: Titoli conseguiti dalla studentessa o dallo studente
      tags:
        - titoli studente
      security: [{}]
      parameters: []
      responses:
        '200':
          description: Richiesta eseguita con successo
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TitoliConseguiti'
              examples:
                Example 1:
                  value:
                    personalData:
                      taxCode: RSSMRA80A01F205D
                      personID: AB123456C
                      givenName: Mario
                      familyName: Rossi
                      birthDate: '1990-05-17'
                      birthPlace: Roma
                    academicQualifications:
                      - _id: 201c59d6a7b800e917c63a1f
                        instituteCode: IFSRM1
                        instituteName: Università degli Studi di Roma 'La Sapienza'
                        titleName: Dottore magistrale
                        courseType: Laurea magistrale
                        courseCode: INF200
                        courseName: Ingegneria
                        classCode: LM-32
                        className: Ingegneria informatica
                        academicQualificationDate: '2022-07-01'
                        gradeValue: '110'
                        GradingScale: 110L
                      - _id: 3f67d91a4b52080005e890cd
                        instituteCode: IFSRM1
                        instituteName: Università degli Studi di Roma 'La Sapienza'
                        titleName: Dottore di ricerca
                        courseType: Dottorato di ricerca
                        courseCode: DR101
                        courseName: Informatica
                        classCode: DR-003
                        className: Intelligenza artificiale
                        academicQualificationDate: '2022-07-01'
                        gradeValue: '-'
                        GradingScale: '-'
                Example 2:
                  value:
                    personalData:
                      taxCode: RSSMRA80A01F205D
                      personID: AB123456C
                      givenName: Mario
                      familyName: Rossi
                      birthDate: '1990-05-17'
                      birthPlace: Roma
                    academicQualifications: []
        '404':
          description: Non sono stati trovati titoli conseguiti per la studentessa o lo studente
        '500':
          description: Errore interno del server
      operationId: titoli-studente
      description: Restituisce la lista dei titoli conseguiti da una studentessa o uno studente
  /status:
    get:
      summary: Verifica stato delle API (Health Check)
      security: [{}]
      operationId: check-status
      description: Verifica lo stato di salute del sistema
      tags:
        - health-check
      responses:
        '204':
          description: il servizio è in esecuzione correttamente.
        '500':
          description: il servizio non è in esecuzione.
components:
  headers:
    Retry-After:
      description: |-
        Retry contacting the endpoint *at least* after seconds.
        See https://tools.ietf.org/html/rfc7231#section-7.1.3
      schema:
        format: int32
        maximum: 186400
        minimum: 0
        type: integer
    X-RateLimit-Limit:
      description: The number of allowed requests in the current period
      schema:
        format: int32
        maximum: 1000000
        minimum: 0
        type: integer
    X-RateLimit-Remaining:
      description: The number of remaining requests in the current period
      schema:
        format: int32
        maximum: 1000000
        minimum: 0
        type: integer
    X-RateLimit-Reset:
      description: The number of seconds left in the current period
      schema:
        format: int32
        maximum: 186400
        minimum: 0
        type: integer
  schemas:
    TitoliConseguiti:
      type: object
      additionalProperties: false
      x-examples:
        Example 1:
          personalData:
            taxCode: RSSMRA80A01F205D
            personID: AB123456C
            givenName: Mario
            familyName: Rossi
            birthDate: '1990-05-17'
            birthPlace: Roma
          academicQualifications:
            - _id: 201c59d6a7b800e917c63a1f
              instituteCode: IFSRM1
              instituteName: Università degli Studi di Roma 'La Sapienza'
              titleName: Dottore magistrale
              courseType: Laurea magistrale
              courseCode: INF200
              courseName: Ingegneria
              classCode: LM-32
              className: Ingegneria informatica
              academicQualificationDate: '2022-07-01'
              gradeValue: '110'
              GradingScale: 110L
            - _id: 3f67d91a4b52080005e890cd
              instituteCode: IFSRM1
              instituteName: Università degli Studi di Roma 'La Sapienza'
              titleName: Dottore di ricerca
              courseType: Dottorato di ricerca
              courseCode: DR101
              courseName: Informatica
              classCode: DR-003
              className: Intelligenza artificiale
              academicQualificationDate: '2022-07-01'
              gradeValue: '-'
              GradingScale: '-'
      description: Anagrafica ed elenco titoli conseguiti da una studentessa o uno studente
      x-stoplight:
        id: 15d3067a4c448
      properties:
        personalData:
          $ref: '#/components/schemas/DatiPersonali'
        academicQualifications:
          description: Elenco dei titoli conseguiti dalla studentessa o dallo studente
          type: array
          maxItems: 256
          minItems: 0
          items:
            $ref: '#/components/schemas/Titolo'
      required:
        - personalData
        - academicQualifications
    Titolo:
      type: object
      additionalProperties: false
      x-jsonld-type: https://w3id.org/italia/onto/yyy/xxx
      x-jsonld-context:
        '@vocab': http://w3id.org/italia/onto/yyy/
        instituteCode: instituteCode
        instituteName: instituteName
        titleName: titleName
        courseType: courseType
        courseCode: courseCode
        courseName: courseName
        classCode: classCode
        className: className 
        academicQualificationDate: academicQualificationDate
        gradeValue: gradeValue
        GradingScale: GradingScale
      x-examples:
        Example 1:
          _id: 201c59d6a7b800e917c63a1f
          instituteCode: IFSRM1
          instituteName: Università degli Studi di Roma 'La Sapienza'
          titleName: Dottore magistrale
          courseType: Laurea magistrale
          courseCode: INF200
          courseName: Ingegneria
          classCode: LM-32
          className: Ingegneria informatica
          academicQualificationDate: '2022-07-01'
          gradeValue: '110'
          GradingScale: 110L
      description: Dettaglio titolo
      properties:
        _id:
          type: string
          description: id del titolo di studio
          minLength: 1
          maxLength: 256
        instituteCode:
          type: string
          description: Codice identificativo dell'istituto
          readOnly: true
          minLength: 1
          maxLength: 10
        instituteName:
          type: string
          description: Nome dell'istituto
          readOnly: true
          minLength: 1
          maxLength: 256
        titleName:
          type: string
          description: Denominazione del titolo di studio
          readOnly: true
          minLength: 1
          maxLength: 256
        courseType:
          type: string
          description: Tipo di corso di studio
          example: laurea, laurea magistrale, dottorato di ricerca, specializzazione, master, formazione professionale
          readOnly: true
          minLength: 1
          maxLength: 256
        courseCode:
          type: string
          description: Codice del corso
          pattern: '^[A-Z\d]{2,4}\d{2,4}$'
          readOnly: true
          minLength: 4
          maxLength: 9
        courseName:
          type: string
          description: Denominazione corso
          example: 'ingegneria, economia, giurisprudenza, medicina, scienze umanistiche, scienze sociali, informatica, arte e design'
          readOnly: true
          minLength: 1
          maxLength: 256
        classCode:
          type: string
          description: Codice identificativo della classe di laurea
          pattern: '^[A-Za-z0-9-]+$'
          example: L-8
          readOnly: true
          minLength: 1
          maxLength: 256
        className:
          type: string
          description: Denominazione della classe di laurea
          example: 'Informatica, Meccanica, Elettronica, Civile'
          readOnly: true
          minLength: 1
          maxLength: 256
        academicQualificationDate:
          type: string
          description: Data di conseguimento del titolo di studio
          pattern: '^[0-9]{4}-[0-9]{2}-[0-9]{2}$'
          example: '2023-05-15'
          format: date
          readOnly: true
        gradeValue: #"prima si chiamava academicQualificationVote"
          type: string
          description: Voto ottenuto al conseguimento del titolo di studio
          pattern: ^(\d+)L?|-$
          minLength: 1
          maxLength: 4          
          example: 110L
          readOnly: true
        GradingScale: #cercare la struttura gradingScale per modificare questo campo "GradingScale" prima si chiamava "courseMaximumGrade"
          type: string
          example: '110'
          pattern: '^\d{1,3}L?|-$'
          minLength: 1
          maxLength: 4     
          description: Voto massimo del corso
          readOnly: true
      required:
        - _id
        - instituteCode
        - instituteName
        - titleName
        - courseType
        - courseCode
        - courseName
        - classCode
        - className
        - academicQualificationDate
        - gradeValue
        - GradingScale
    DatiPersonali:
      type: object
      additionalProperties: false
      x-jsonld-type: https://w3id.org/italia/onto/CPV/Person
      x-jsonld-context:
        '@vocab': http://w3id.org/italia/onto/CPV/
        givenName: givenName
        taxCode: taxCode
        familyName: familyName
        birthDate: dateOfBirth
        birthPlace: hasBirthPlace
        personID: personID         
      x-examples:
        Example 1:
          taxCode: RSSMRA80A01F205D
          personID: AB123456C
          givenName: Mario
          familyName: Rossi
          birthDate: '1990-05-17'
          birthPlace: Roma
      description: Dati personali della studentessa o dello studente
      properties:
        taxCode:
          type: string
          description: Codice Fiscale
          example: RSSMRA80A01F205D
          pattern: '^[A-Z]{6}\d{2}[A-Z]\d{2}[A-Z]\d{3}[A-Z]$'
          minLength: 16
          maxLength: 16
          readOnly: true
        personID:
          type: string
          description: Identificativo ANPR
          maxLength: 9
          minLength: 9
          pattern: '^[A-Z0-9]{8}[A-Z]$'
          example: AB123456C
          readOnly: true
        givenName:
          type: string
          description: Nome
          example: Mario
          pattern: '^[A-ZÀ-ÖØ-Ýa-zà-öø-ý\s''-]+$'
          readOnly: true
          minLength: 1
          maxLength: 256
        familyName:
          type: string
          description: Cognome
          example: Rossi
          pattern: '^[A-ZÀ-ÖØ-Ýa-zà-öø-ý\s''-]+$'
          readOnly: true
          minLength: 1
          maxLength: 256
        birthDate:
          type: string
          format: date
          example: '1990-05-17'
          pattern: '^\d{4}-\d{2}-\d{2}$'
          description: Data di nascita
          readOnly: true
        birthPlace:
          type: string
          example: Rome
          description: Luogo di nascita
          readOnly: true
          minLength: 1
          maxLength: 256
      required:
        - taxCode
        - personID
        - givenName
        - familyName
        - birthDate
        - birthPlace
  requestBodies: {}
  responses: {}
servers:
  - url: 'https://localhost:8080/api'
    description: localhost
tags:
  - name: titoli studente
  - name: health-check
