openapi: 3.0.0
x-stoplight:
  id: 0f56e32f16f60
info:
  title: IFS02 - Retrieve enrollment details / Recupero dettaglio iscrizioni 
  x-summary: Enrollment detail of a student / Dettaglio iscrizioni di una studentessa o uno studente 
  version: 1.0.0
  description: |
   Provides detailed information regarding the enrollment of student at a public university or AFAM / Fornisce informazioni di dettaglio riguardanti le iscrizioni di una studentessa o uno studente all'università o AFAM pubblico
  contact:
    name: helpdesk
    email: helpdesk@gmail.com
  x-api-id: 00000000-0000-0000-0000-000000000000
  termsOfService: 'http://swagger.io/terms/'
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
paths:
  '/students/Enrollments':
    parameters:
        - name: PersonID
          in: query
          required: false
          schema:
            type: string
            maxLength: 9
            minLength: 9
            description: ANPR Identifier / Identificativo ANPR 
            pattern: "^[A-Z0-9]{8}[A-Z]$"
        - name: taxCode
          in: query
          required: false
          schema:
            type: string
            maxLength: 16
            minLength: 16
            description: Codice Fiscale / Tax Identification Number 
            pattern: "^([a-zA-Z]{6}[0-9L-Nl-nP-Vp-v]{2}[A-Ea-eHhLlMmPpRrSsTt][0-9L-Nl-nP-Vp-v]{2}[a-zA-Z][0-9L-Nl-nP-Vp-v]{3}[a-zA-Z])$"    
    get:
      summary: Retrieve enrollment details of student / Recupero iscrizioni di una studentessa o di uno studente 
      tags:
        - iscrizioni
      security: [{}]
      responses:
        '200':
          description: Request successfully executed / Richiesta eseguita con successo
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StudentdEnrollments'
              examples:
                Example 1:
                  value:
                    PersonalData:
                      taxCode: RSSMRA80A01F205D
                      personID: AB123456C
                      givenName: Mario
                      familyName: Rossi
                      birthDate: '1990-05-17'
                      birthPlace: Roma
                    Enrollments:
                      - instituteCode: 16
                        instituteName: Milano - Politecnico
                        courseType: Corso di laurea
                        courseCode: INF101
                        courseName: Ingegneria
                        classCode: L-8
                        className: Ingegneria informatica
                        academicYear: 2021/2022
                        courseYear: 3
                      - instituteCode: C6
                        instituteName: Milano-Bicocca - Università degli studi
                        courseType: Corso di laurea magistrale
                        courseCode: INF200
                        courseName: Ingegneria informatica
                        classCode: LM-32
                        className: Ingegneria informatica
                        academicYear: 2022/2023
                        courseYear: 1
                Example 2:
                  value:
                    PersonalData:
                      taxCode: RSSMRA80A01F205D
                      personID: AB123456C
                      givenName: Mario
                      familyName: Rossi
                      birthDate: '1990-05-17'
                      birthPlace: Roma
                    Enrollments: []
        '400':
          description: One of the input fields appears to be missing / Risulta mancante uno dei campi di input
        '404':
          description: No enrollments were found for the student at this institution / Non sono state trovate iscrizioni per la studentessa o lo studente in questo istituto
        '500':
          description: Internal server error / Errore interno del server 
      operationId: Enrollments-of-student
      description:  Returns the enrollment details of student / Restituisce i dettagli delle iscrizioni di una studentessa o di uno studente
      parameters: []
  /status:
    get:
      summary: Verifica stato delle API (Health Check)
      security: [{}]
      operationId: check-status
      description: Check the system's health status / Verificare lo stato di salute del sistema 
      tags:
        - health-check
      responses:
        '204':
          description: The service is running correctly / Il servizio è in esecuzione correttamente
        '500':
          description:  The service is not running. / Il servizio non è in esecuzione. 
components:
  headers:
    Retry-After:
      description: |-
        Retry contacting the endpoint *at least* after seconds.
        See https://tools.ietf.org/html/rfc7231#section-7.1.3
      schema:
        format: int32
        maximum: 186400
        minimum: 0
        type: integer
    X-RateLimit-Limit:
      description: The number of allowed requests in the current period / Numero di richieste consentite nel periodo attuale
      schema:
        format: int32
        maximum: 1000000
        minimum: 0
        type: integer
    X-RateLimit-Remaining:
      description: The number of remaining requests in the current period / Numero di richieste rimanenti nel periodo attuale 
      schema:
        format: int32
        maximum: 1000000
        minimum: 0
        type: integer
    X-RateLimit-Reset:
      description: The number of seconds left in the current period / Numero di secondi rimanenti nel periodo attuale
      schema:
        format: int32
        maximum: 186400
        minimum: 0
        type: integer
  schemas:
    StudentdEnrollments:
      additionalProperties: false
      type: object
      x-examples:
        Example 1:
          PersonalData:
            taxCode: RSSMRA80A01F205D
            personID: AB123456C
            givenName: Mario
            familyName: Rossi
            birthDate: '1990-05-17'
            birthPlace: Roma
          Enrollments:
            - instituteCode: 16
              instituteName: Milano - Politecnico
              courseType: Corso di laurea
              courseCode: INF101
              courseName: Ingegneria
              classCode: L-8
              className: Ingegneria informatica
              academicYear: 2021/2022
              courseYear: 3
            - instituteCode: C6
              instituteName: Milano-Bicocca - Università degli studi
              courseType: Corso di laurea magistrale
              courseCode: INF200
              courseName: Ingegneria informatica
              classCode: LM-32
              className: Ingegneria informatica
              academicYear: 2022/2023
              courseYear: 1
      description: Enrollment details of student / Dettaglio iscrizioni di una studentessa o di uno studente
      x-stoplight:
        id: 22de4be4ac251
      properties:
        PersonalData:
          $ref: '#/components/schemas/PersonalData'
        Enrollments:
          type: array
          maxItems: 256
          minItems: 0
          description: List of enrollments for student / Elenco iscrizioni di una studentessa o di uno studente
          items:
            $ref: '#/components/schemas/Enrollment'
      required:
        - PersonalData
        - Enrollments
    Enrollment:
      type: object
      additionalProperties: false
      x-jsonld-type: https://w3id.org/italia/onto/yyy/xxx
      x-jsonld-context:
        '@vocab': http://w3id.org/italia/onto/yyy/
        instituteCode: instituteCode
        instituteName: instituteName
        courseType: courseType
        courseCode: courseCode
        courseName: courseName
        classCode: classCode
        className: className
        academicYear: academicYear
        courseYear: courseYear
      x-examples:
        Example 1:
          instituteCode: 16
          instituteName: Milano - Politecnico
          courseType: Corso di laurea
          courseCode: INF101
          courseName: Ingegneria
          classCode: L-8
          className: Ingegneria informatica
          academicYear: 2021/2022
          courseYear: 3
      description: Detailed enrollment information / Informazioni dettagliate sull'iscrizione
      properties:
        instituteCode:
          type: string
          description: Institutional identification code / Codice identificativo dell’istituto  [** DA DEFINIRE PATTERN CORRETTO **]
          example: '16'
          readOnly: true
          minLength: 2
          maxLength: 2
        instituteName:
          type: string
          description: Institution name / Denominazione dell’istituto
          example: 'Milano - Politecnico'
          readOnly: true
          minLength: 1
          maxLength: 256
        courseType:
          type: string
          description: Type of study program / Tipologia del corso di studio
          example: 'laurea, laurea magistrale, dottorato di ricerca, specializzazione, master, formazione professionale'
          readOnly: true
          minLength: 1
          maxLength: 256
        courseCode:
          type: string
          description: Course code / Codice del corso [** DA DEFINIRE PATTERN CORRETTO **]
          #pattern: '^[A-Z\d]{2,4}\d{2,4}$'
          readOnly: true
          minLength: 4
          maxLength: 20
        courseName:
          type: string
          description: Course name / Denominazione corso
          example: 'ingegneria, economia, giurisprudenza, medicina, scienze umanistiche, scienze sociali, informatica, arte e design'
          readOnly: true
          minLength: 1
          maxLength: 256
        classCode:
          type: string
          description: Identification code of the degree class / Codice identificativo della classe di laurea [** DA DEFINIRE PATTERN CORRETTO **]
          #pattern: '^[A-Z]+-\d{1,2}$'
          example: L-8
          readOnly: true
          minLength: 2
          maxLength: 20
        className:
          type: string
          description: Name of the degree class / Denominazione della classe di laurea 
          example: 'Informatica, Meccanica, Elettronica, Civile'
          readOnly: true
          minLength: 1
          maxLength: 256
        academicYear:
          type: string
          description: Last academic year in which enrollment in the student's course is recorded / Ultimo anno accademico in cui risulta l'iscrizione al corso della studentessa o dello studente 
          example: 2022/2023
          pattern: '^\d{4}/\d{4}$'
          readOnly: true
          minLength: 9
          maxLength: 9
        courseYear:
          type: string
          description: Last year in which enrollment in the student's course is recorded / Ultimo anno in cui risulta l'iscrizione al corso della studentessa o dello studente
          example: 3
          pattern: ^\d{2}$
          readOnly: true
          minLength: 2
          maxLength: 2
      required:
        - instituteCode
        - instituteName
        - courseType
        - courseCode
        - courseName
        - classCode
        - className
        - academicYear
        - courseYear
    PersonalData:
      type: object
      additionalProperties: false
      x-jsonld-type: https://w3id.org/italia/onto/CPV/Person
      x-jsonld-context:
        '@vocab': http://w3id.org/italia/onto/CPV/
        givenName: givenName
        taxCode: taxCode
        familyName: familyName
        birthDate: dateOfBirth
        birthPlace: hasBirthPlace
        personID: personID      
      x-examples:
        Example 1:
          taxCode: RSSMRA80A01F205D
          personID: AB123456C
          givenName: Mario
          familyName: Rossi
          birthDate: '1990-05-17'
          birthPlace: Roma
      description: Personal data of the student / Dati personali della studentessa o dello studente
      properties:
        taxCode:
          type: string
          description: Tax Identification Number / Codice Fiscale
          example: RSSMRA80A01F205D
          pattern: '^[A-Z]{6}\d{2}[A-Z]\d{2}[A-Z]\d{3}[A-Z]$'
          minLength: 16
          maxLength: 16
          readOnly: true
        personID:
          type: string
          description: ANPR Identifier / Identificativo ANPR 
          maxLength: 9
          minLength: 9
          pattern: '^[A-Z0-9]{8}[A-Z]$'
          example: AB123456C
          readOnly: true
        givenName:
          type: string
          description: Name / Nome
          example: Mario
          pattern: '^[A-ZÀ-ÖØ-Ýa-zà-öø-ý\s''-]+$'
          readOnly: true
          minLength: 1
          maxLength: 256
        familyName:
          type: string
          description: Surname / Cognome
          example: Rossi
          pattern: '^[A-ZÀ-ÖØ-Ýa-zà-öø-ý\s''-]+$'
          readOnly: true
          minLength: 1
          maxLength: 256
        birthDate:
          type: string
          format: date
          example: '1990-05-17'
          pattern: '^\d{4}-\d{2}-\d{2}$'
          description: Date of birth / Data di nascita
          readOnly: true
        birthPlace:
          type: string
          example: Rome
          description: Place of birth / Luogo di nascita
          readOnly: true
          minLength: 1
          maxLength: 256
      required:
        - taxCode
        - personID
        - givenName
        - familyName
        - birthDate
        - birthPlace
  requestBodies: {}
  responses: {}
servers:
  - url: 'https://localhost:8080/api'
    description: localhost
tags:
  - name: iscrizioni
  - name: health-check
