openapi: 3.0.0
x-stoplight:
  id: 0f56e32f16f60
info:
  title: IFS09 - Iscritti a un corso per anno
  x-summary: Acquisisce il numero di studentesse e studenti iscritti a uno specifico corso per anno accademico
  version: 1.0.0
  description: |
    Ottiene il numero di studentesse e di studenti iscritti ad un IFS.
  contact:
    name: helpdesk
    email: helpdesk@gmail.com
  x-api-id: 00000000-0000-0000-0000-000000000000
  termsOfService: 'http://swagger.io/terms/'
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
paths:
  /stats/iscritti:
    get:
      summary: Iscritti
      tags:
        - iscritti
      security: [{}] 
      responses:
        '200':
          description: Richiesta eseguita con successo
          content:
            application/json:
              schema:
                type: object
                additionalProperties: false
                properties:
                  instituteName:
                    type: string
                    description: Nome dell'istituto
                    readOnly: true
                    minLength: 1
                    maxLength: 256                       
                  courseName:
                    type: string
                    description: Nome del Corso di studi
                    readOnly: true
                    minLength: 1
                    maxLength: 256                       
                  academicYear:
                    type: string
                    example: 2022-2023
                    pattern: '^\d{4}-\d{4}$'
                    description: Anno accademico
                    readOnly: true
                    minLength: 9
                    maxLength: 9                       
                  numberRegistered:
                    type: integer
                    description: 'Numero di iscritti all''IFS, facoltà o corso '
                    format: int32
                    minimum: 0
                    maximum: 500000
                    readOnly: true
                required:
                  - instituteName
                  - numberRegistered
              examples:
                Example 1:
                  value:
                    courseName: Ingegneria Informatica
                    academicYear: 2022-2023
                    numberRegistered: 48
                Example 2:
                  value:
                    instituteName: Università degli Studi di Roma 'La Sapienza'
                    academicYear: 2022-2023
                    numberRegistered: 1200
        '500':
          description: Errore interno del server
      operationId: iscritti-per-isee
      description: 'Restituisce il numero di studentesse e di studenti iscritti. Valorizzando i queryParams opzionali (courseName e academicYear) è possibile filtrare i risultati. Non valorizzandoli il risultato ottenuto si riferirà all''IFS per intero.'
      parameters:
        - schema:
            type: string
            minLength: 1
            maxLength: 256               
          in: query
          name: courseName
          description: Nome del corso di studi
        - schema:
            type: string
            pattern: '^\d{4}-\d{4}$'
            example: 2022-2023
            minLength: 9
            maxLength: 9               
          in: query
          name: academicYear
          description: 'Anno accademico '
  /status:
    get:
      summary: Verifica stato delle API (Health Check)
      operationId: check-status
      description: Verificare lo stato di salute del sistema
      tags:
        - health-check
      security: [{}]       
      responses:
        '204':
          description: il servizio è in esecuzione correttamente.
        '500':
          description: il servizio non è in esecuzione.
components:
  headers:
    Retry-After:
      description: |-
        Retry contacting the endpoint *at least* after seconds.
        See https://tools.ietf.org/html/rfc7231#section-7.1.3
      schema:
        format: int32
        maximum: 186400
        minimum: 0
        type: integer
    X-RateLimit-Limit:
      description: The number of allowed requests in the current period
      schema:
        format: int32
        maximum: 1000000
        minimum: 0
        type: integer
    X-RateLimit-Remaining:
      description: The number of remaining requests in the current period
      schema:
        format: int32
        maximum: 1000000
        minimum: 0
        type: integer
    X-RateLimit-Reset:
      description: The number of seconds left in the current period
      schema:
        format: int32
        maximum: 186400
        minimum: 0
        type: integer  
  schemas: {}
  requestBodies: {}
  responses: {}
servers:
  - url: 'https://localhost:8080/api'
    description: localhost
tags:
  - name: health-check
  - name: iscritti
