openapi: 3.0.0
x-stoplight:
  id: 0f56e32f16f60
info:
  title: IFS03 - Titoli studente
  x-summary: Questo servizio ritorna l'elenco dei titoli conseguiti da uno/a studente.
  version: 1.0.0
  description: |
    Restituisce l'elenco dei titoli conseguiti da uno/a studente
  contact:
    name: helpdesk
    email: helpdesk@mail.edu.it
  x-api-id: 00000000-0000-0000-0000-000000000000
  termsOfService: 'http://swagger.io/terms/'
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
paths:
  '/studenti/{taxCode}/titoli':
    parameters:
      - schema:
          type: string
        name: taxCode
        in: path
        required: true
        description: 'Codice Fiscale '
    get:
      summary: Titoli conseguiti dallo/a studente
      tags:
        - titoli studente
      parameters: []
      responses:
        '200':
          description: Richiesta eseguita con successo
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TitoliConseguiti'
              examples:
                Example 1:
                  value:
                    personalData:
                      taxCode: RSSMRA80A01F205D
                      personID: AB123456C
                      givenName: Mario
                      familyName: Rossi
                      birthDate: '1990-05-17'
                      birthPlace: Roma
                    academicQualifications:
                      - _id: 201c59d6a7b800e917c63a1f
                        instituteCode: IFSRM1
                        instituteName: Università degli Studi di Roma 'La Sapienza'
                        titleName: Dottore magistrale
                        courseType: Laurea magistrale
                        courseCode: INF200
                        courseName: Ingegneria
                        classCode: LM-32
                        className: Ingegneria informatica
                        academicQualificationDate: '2022-07-01'
                        academicQualificationVote: '110'
                        courseMaximumGrade: 110L
                      - _id: 3f67d91a4b52080005e890cd
                        instituteCode: IFSRM1
                        instituteName: Università degli Studi di Roma 'La Sapienza'
                        titleName: Dottore di ricerca
                        courseType: Dottorato di ricerca
                        courseCode: DR101
                        courseName: Informatica
                        classCode: DR-003
                        className: Intelligenza artificiale
                        academicQualificationDate: '2022-07-01'
                        academicQualificationVote: '-'
                        courseMaximumGrade: '-'
                Example 2:
                  value:
                    personalData:
                      taxCode: RSSMRA80A01F205D
                      personID: AB123456C
                      givenName: Mario
                      familyName: Rossi
                      birthDate: '1990-05-17'
                      birthPlace: Roma
                    academicQualifications: []
        '404':
          description: Non sono stati trovati titoli conseguiti per lo/a studente
        '500':
          description: Errore interno del server
      operationId: titoli-studente
      description: Restituisce la lista dei titoli conseguiti da uno/a studente
  /status:
    get:
      summary: Verifica stato delle API (Health Check)
      operationId: check-status
      description: Verifica lo stato di salute del sistema
      tags:
        - health-check
      responses:
        '204':
          description: il servizio è in esecuzione correttamente.
        '500':
          description: il servizio non è in esecuzione.
components:
  schemas:
    TitoliConseguiti:
      type: object
      x-examples:
        Example 1:
          personalData:
            taxCode: RSSMRA80A01F205D
            personID: AB123456C
            givenName: Mario
            familyName: Rossi
            birthDate: '1990-05-17'
            birthPlace: Roma
          academicQualifications:
            - _id: 201c59d6a7b800e917c63a1f
              instituteCode: IFSRM1
              instituteName: Università degli Studi di Roma 'La Sapienza'
              titleName: Dottore magistrale
              courseType: Laurea magistrale
              courseCode: INF200
              courseName: Ingegneria
              classCode: LM-32
              className: Ingegneria informatica
              academicQualificationDate: '2022-07-01'
              academicQualificationVote: '110'
              courseMaximumGrade: 110L
            - _id: 3f67d91a4b52080005e890cd
              instituteCode: IFSRM1
              instituteName: Università degli Studi di Roma 'La Sapienza'
              titleName: Dottore di ricerca
              courseType: Dottorato di ricerca
              courseCode: DR101
              courseName: Informatica
              classCode: DR-003
              className: Intelligenza artificiale
              academicQualificationDate: '2022-07-01'
              academicQualificationVote: '-'
              courseMaximumGrade: '-'
      description: Anagrafica ed elenco titoli conseguiti da uno/a studente
      x-stoplight:
        id: 15d3067a4c448
      properties:
        personalData:
          $ref: '#/components/schemas/Studente'
        academicQualifications:
          description: Elenco dei titoli conseguiti dallo/a studente
          type: array
          items:
            $ref: '#/components/schemas/Titolo'
      required:
        - personalData
        - academicQualifications
    Titolo:
      type: object
      x-examples:
        Example 1:
          _id: 201c59d6a7b800e917c63a1f
          instituteCode: IFSRM1
          instituteName: Università degli Studi di Roma 'La Sapienza'
          titleName: Dottore magistrale
          courseType: Laurea magistrale
          courseCode: INF200
          courseName: Ingegneria
          classCode: LM-32
          className: Ingegneria informatica
          academicQualificationDate: '2022-07-01'
          academicQualificationVote: '110'
          courseMaximumGrade: 110L
      description: Dettaglio titolo
      properties:
        _id:
          type: string
          description: id del titolo di studio dello/a studente
        instituteCode:
          type: string
          description: Codice identificativo dell'istituto
          readOnly: true
        instituteName:
          type: string
          description: Nome dell'istituto
          readOnly: true
        titleName:
          type: string
          description: Denominazione del titolo di studio
          readOnly: true
        courseType:
          type: string
          description: Tipo di corso di studio
          example: laurea, laurea magistrale, dottorato di ricerca, specializzazione, master, formazione professionale
          readOnly: true
        courseCode:
          type: string
          description: Codice corso
          readOnly: true
        courseName:
          type: string
          description: Denominazione del corso di studio
          example: ingegneria, economia, giurisprudenza, medicina, scienze umanistiche, scienze sociali, informatica, arte e design
          readOnly: true
        classCode:
          type: string
          description: Codice della classe di studio
          pattern: '^[A-Za-z0-9-]+$'
          example: L-8
          readOnly: true
        className:
          type: string
          description: Denominazione della classe di studio
          example: Informatica, Meccanica, Elettronica, Civile
          readOnly: true
        academicQualificationDate:
          type: string
          description: Data di conseguimento del titolo di studio
          pattern: '^[0-9]{4}-[0-9]{2}-[0-9]{2}$'
          example: '2023-05-15'
          format: date
          readOnly: true
        academicQualificationVote:
          type: string
          description: Voto ottenuto al conseguimento del titolo di studio
          pattern: ^(\d+)L?|-$
          example: 110L
          readOnly: true
        courseMaximumGrade:
          type: string
          example: '110'
          pattern: '^\d{1,3}L?|-$'
          description: Voto massimo del corso
          readOnly: true
      required:
        - _id
        - instituteCode
        - instituteName
        - titleName
        - courseType
        - courseCode
        - courseName
        - classCode
        - className
        - academicQualificationDate
        - academicQualificationVote
        - courseMaximumGrade
    Studente:
      type: object
      x-examples:
        Example 1:
          taxCode: RSSMRA80A01F205D
          personID: AB123456C
          givenName: Mario
          familyName: Rossi
          birthDate: '1990-05-17'
          birthPlace: Roma
      description: Dati personali studente
      properties:
        taxCode:
          type: string
          description: Codice Fiscale Studente
          example: RSSMRA80A01F205D
          pattern: '^[A-Z]{6}\d{2}[A-Z]\d{2}[A-Z]\d{3}[A-Z]$'
          minLength: 16
          maxLength: 16
          readOnly: true
        personID:
          type: string
          description: Identificativo ANPR
          maxLength: 9
          minLength: 9
          pattern: '^[A-Z0-9]{8}[A-Z]$'
          example: AB123456C
          readOnly: true
        givenName:
          type: string
          description: Nome Studente
          example: Mario
          pattern: '^[A-ZÀ-ÖØ-Ýa-zà-öø-ý\s''-]+$'
          readOnly: true
        familyName:
          type: string
          description: Cognome Studente
          example: Rossi
          pattern: '^[A-ZÀ-ÖØ-Ýa-zà-öø-ý\s''-]+$'
          readOnly: true
        birthDate:
          type: string
          format: date
          example: '1990-05-17'
          pattern: '^\d{4}-\d{2}-\d{2}$'
          description: Data di nascita studente
          readOnly: true
        birthPlace:
          type: string
          example: Rome
          description: Luogo di nascita studente
          readOnly: true
      required:
        - taxCode
        - personID
        - givenName
        - familyName
        - birthDate
        - birthPlace
  requestBodies: {}
  responses: {}
servers:
  - url: 'https://localhost:8080/api'
    description: localhost
tags:
  - name: titoli studente
  - name: health-check