openapi: 3.0.0
x-stoplight:
  id: 0f56e32f16f60
info:
  title: API riferimento ANIS
  x-summary: Questo servizio ritorna l'elenco degli iscritti a un ifs.
  version: 1.0.0
  description: |
    ### Documentazione

    ## API riferimento ANIS
    La seguente documentazione API fornisce un riferimento per l'integrazione e 
    l'accesso ai dati ANIS (ANagrafe degli Studenti) relativi alle università. 
    Queste API consentono l'erogazione di servizi (e-service) che operano sui dati ANIS.

    # API Health Check

    L'API Health Check fornisce un modo semplice per verificare lo stato di salute del sistema. 
    È un endpoint di base che può essere utilizzato per controllare se il servizio è in esecuzione correttamente.

    **Endpoint:**  **Endpoint:**   GET  api/status


    # Studenti iscritti presso quell'IFS
    Questa API restituisce un elenco di studenti iscritti presso un determinato IFS (Istituto di Formazione Superiore). 
    L'elenco è collegato ai Codici Fiscali (CF) o agli identificativi ANPR reperibili da ANPR tramite il CF 
    o altre fonti fornite dall'IFS.

    **Endpoint:**   GET  api/studenti/iscritti

    **Esempio di risposta:**

    ```json
    {
      "denominazione_ifs": "Istituto Tecnologie Avanzate",
      "studenti": [
        {
          "codice_fiscale": "RSSMRA80A01F205D",
          "anpr_id": "AB123456C",
          "nome_proprio": "Mario",
          "cognome": "Rossi"
        },
        {
          "codice_fiscale": "VRDLCU90A01H501L",
          "anpr_id": "ANPR4567D",
          "nome_proprio": "Luca",
          "cognome": "Verdi"
        }
      ]
    }
  contact:
    name: helpdesk
    email: helpdesk@gmail.com
  x-api-id: 00000000-0000-0000-0000-000000000000
  termsOfService: 'http://swagger.io/terms/'
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
paths:
  /status:
    get:
      summary: Health Check
      operationId: check-status
      description: Verificare lo stato di salute del sistema
      tags:
        - HEALTH-CHECK
      responses:
        '204':
          description: il servizio è in esecuzione correttamente.
        '500':
          description: il servizio non è in esecuzione.
  /studenti/iscritti:
    get:
      summary: Studenti iscritti presso IFS
      parameters: []
      responses:
        '200':
          description: Richiesta eseguita con successo
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StudentiIscritti'
              examples:
                Example 1:
                  value:
                    denominazione_ifs: Istituto Tecnologie Avanzate
                    studenti:
                      - codice_fiscale: RSSMRA80A01F205D
                        anpr_id: AB123456C
                        nome_proprio: Mario
                        cognome: Rossi
                      - codice_fiscale: VRDLCU90A01H501L
                        anpr_id: ANPR4567D
                        nome_proprio: Luca
                        cognome: Verdi
                Example 2:
                  value:
                    denominazione_ifs: Istituto Tecnologie Avanzate
                    studenti: []
        '500':
          description: Errore interno del server
      description: Restituisce la lista degli studenti iscritti presso l'IFS
      operationId: studenti-iscritti
      tags:
        - STUDENTI-ISCRITTI
    parameters: []
components:
  schemas:
    StudentiIscritti:
      type: object
      x-examples:
        Example 1:
          denominazione_ifs: Nome istituto
          studenti:
            - codice_fiscale: '1234567890'
              anpr_id: ANPR123
              nome_proprio: Mario
              cognome: Rossi
            - codice_fiscale: '0987654321'
              anpr_id: ANPR456
              nome_proprio: Luca
              cognome: Verdi
      x-stoplight:
        id: 582aaf1b98185
      description: Studenti iscritti a quell'istituto
      properties:
        denominazione_ifs:
          type: string
          description: Denominazione dell’istituto
          readOnly: true
        studenti:
          type: array
          description: Lista studenti iscritti
          items:
            type: object
            properties:
              codice_fiscale:
                type: string
                description: 'Codice Fiscale Studente '
                example: RSSMRA80A01F205D
                pattern: '^[A-Z]{6}\d{2}[A-Z]\d{2}[A-Z]\d{3}[A-Z]$'
                minLength: 16
                maxLength: 16
                readOnly: true
              anpr_id:
                type: string
                description: Identificativo ANPR
                maxLength: 9
                minLength: 9
                pattern: '^[A-Z0-9]{8}[A-Z]$'
                example: AB123456C
                readOnly: true
              nome_proprio:
                type: string
                description: 'Nome Studente '
                example: Mario
                pattern: '^[A-ZÀ-ÖØ-Ýa-zà-öø-ý\s''-]+$'
                readOnly: true
              cognome:
                type: string
                description: Cognome Studente
                example: Rossi
                pattern: '^[A-ZÀ-ÖØ-Ýa-zà-öø-ý\s''-]+$'
                readOnly: true
  requestBodies: {}
  responses: {}
servers:
  - url: 'https://localhost:8080/api'
    description: localhost
tags:
  - name: API-ANIS
  - name: HEALTH-CHECK
  - name: STUDENTI-ISCRITTI
