openapi: 3.0.0
x-stoplight:
  id: 0f56e32f16f60
info:
  title: API riferimento ANIS
  x-summary: 'Questo servizio ritorna l''elenco degli iscritti a uno specifico corso di un IFS, raggruppati per anno.'
  version: 1.0.0
  description: |
    ### Documentazione

    ## API riferimento ANIS
    La seguente documentazione API fornisce un riferimento per l'integrazione e 
    l'accesso ai dati ANIS (ANagrafe degli Studenti) relativi alle università. 
    Queste API consentono l'erogazione di servizi (e-service) che operano sui dati ANIS.

    # API Health Check
    Questa API fornisce un modo semplice per verificare lo stato di salute del sistema. 
    È un endpoint di base che può essere utilizzato per controllare se il servizio è in esecuzione correttamente.

    **Endpoint:**   GET  /status


    # Studenti iscritti a un corso di studi raggruppati per anno di corso
    Questa API consente di ottenere il numero di studenti iscritti a uno specifico Corso di Studi di un IFS, suddivisi per anno di corso. Restituisce i dati relativi al corso e il conteggio degli studenti iscritti a ciascun anno.

    **Endpoint:**   GET  /corsi/{courseName}/iscritti-per-anno

    **Params:**    `{courseName}`: Nome del corso di studi.

    **Esempio di risposta:**

    ```json
    {
      "instituteName": "Università degli Studi di Milano",
      "courseType": "Laurea",
      "courseName": "Ingegneria",
      "classCode": "LM-23",
      "className": "Civile e Ambientale",
      "registeredPerYear": {
        "firstYear": 50,
        "secondYear": 40,
        "thirdYear": 30
      }
    }
  contact:
    name: helpdesk
    email: helpdesk@gmail.com
  x-api-id: 00000000-0000-0000-0000-000000000000
  termsOfService: 'http://swagger.io/terms/'
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
paths:
  /status:
    get:
      summary: Health Check
      operationId: check-status
      description: Verificare lo stato di salute del sistema
      tags:
        - HEALTH-CHECK
      responses:
        '204':
          description: il servizio è in esecuzione correttamente.
        '500':
          description: il servizio non è in esecuzione.
  '/corsi/{courseName}/iscritti-per-anno':
    parameters:
      - schema:
          type: string
        name: courseName
        in: path
        required: true
        description: Nome del corso di studi
    get:
      summary: Studenti iscritti a quel Corso di Studi raggruppati per anno di corso
      tags:
        - STUDENTI-ANNO-CORSO
      responses:
        '200':
          description: Richiesta eseguita con successo
          headers:
            Content-Length:
              schema:
                type: integer
                format: int64
              description: 'utilizzato per indicare la dimensione del corpo della risposta, consentendo al client di gestire correttamente la ricezione dei dati.'
            Cache-Control:
              schema:
                type: string
              description: 'utilizzato per indicare al client o ai server intermedi come gestire la memorizzazione nella cache della risposta, ad esempio "no-cache" per impedire la memorizzazione nella cache.'
            Access-Control-Allow-Origin:
              schema:
                type: string
              description: utilizzato per consentire a determinati origini di accedere alle risorse tramite richieste cross-origin.
            X-RateLimit-Limit:
              schema:
                type: integer
                format: int64
              description: specifica il numero massimo di richieste consentite entro un determinato periodo di tempo (solitamente misurato in secondi).
            X-RateLimit-Remaining:
              schema:
                type: integer
                format: int64
              description: utilizzato per indicare il numero di richieste API rimanenti all'interno del periodo di tempo specificato dal server.
            X-RateLimit-Reset:
              schema:
                type: string
                format: date-time
              description: utilizzato per indicare il momento in cui il limite delle richieste API verrà ripristinato.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StudentiAnnoCorso'
              examples:
                Example 1:
                  value:
                    instituteName: Università degli Studi di Milano
                    courseType: Laurea
                    courseName: Ingegneria
                    classCode: LM-23
                    className: Civile e Ambientale
                    registeredPerYear:
                      firstYear: 50
                      secondYear: 40
                      thirdYear: 30
        '404':
          description: Corso di studi non trovato
          headers:
            Content-Length:
              schema:
                type: integer
                format: int64
              description: 'utilizzato per indicare la dimensione del corpo della risposta, consentendo al client di gestire correttamente la ricezione dei dati.'
            Cache-Control:
              schema:
                type: string
              description: 'utilizzato per indicare al client o ai server intermedi come gestire la memorizzazione nella cache della risposta, ad esempio "no-cache" per impedire la memorizzazione nella cache.'
            Access-Control-Allow-Origin:
              schema:
                type: string
              description: utilizzato per consentire a determinati origini di accedere alle risorse tramite richieste cross-origin.
            X-RateLimit-Limit:
              schema:
                type: integer
                format: int64
              description: specifica il numero massimo di richieste consentite entro un determinato periodo di tempo (solitamente misurato in secondi).
            X-RateLimit-Remaining:
              schema:
                type: integer
                format: int64
              description: utilizzato per indicare il numero di richieste API rimanenti all'interno del periodo di tempo specificato dal server.
            X-RateLimit-Reset:
              schema:
                type: string
                format: date-time
              description: utilizzato per indicare il momento in cui il limite delle richieste API verrà ripristinato.
        '500':
          description: Errore Interno del Server
          headers:
            Content-Length:
              schema:
                type: integer
                format: int64
              description: 'utilizzato per indicare la dimensione del corpo della risposta, consentendo al client di gestire correttamente la ricezione dei dati.'
            Cache-Control:
              schema:
                type: string
              description: 'utilizzato per indicare al client o ai server intermedi come gestire la memorizzazione nella cache della risposta, ad esempio "no-cache" per impedire la memorizzazione nella cache.'
            Access-Control-Allow-Origin:
              schema:
                type: string
              description: utilizzato per consentire a determinati origini di accedere alle risorse tramite richieste cross-origin.
            X-RateLimit-Limit:
              schema:
                type: integer
                format: int64
              description: specifica il numero massimo di richieste consentite entro un determinato periodo di tempo (solitamente misurato in secondi).
            X-RateLimit-Remaining:
              schema:
                type: integer
                format: int64
              description: utilizzato per indicare il numero di richieste API rimanenti all'interno del periodo di tempo specificato dal server.
            X-RateLimit-Reset:
              schema:
                type: string
                format: date-time
              description: utilizzato per indicare il momento in cui il limite delle richieste API verrà ripristinato.
      operationId: studenti-iscritti-per-anno-corso
      description: Restituisce il numero di studenti iscritti a un Corso di studi specifico raggruppati per anno di corso
      parameters:
        - schema:
            type: string
          in: header
          name: Method
          description: Specifica il metodo HTTP utilizzato per la richiesta.
        - schema:
            type: string
          in: header
          name: Path
          description: Specifica il percorso o l'endpoint dell'API a cui viene indirizzata la richiesta.
        - schema:
            type: string
          in: header
          name: Scheme
          description: 'Specifica lo schema o il protocollo utilizzato per la comunicazione tra il client e il server, come HTTP o HTTPS.'
        - schema:
            type: string
          in: header
          name: Accept-Encoding
          description: 'Utilizzato per indicare al server le opzioni di compressione supportate dal client, come gzip o deflate.'
        - schema:
            type: string
          in: header
          name: Accept-Language
          description: 'Utilizzato per indicare al server la lingua preferita per la risposta, in modo che possa restituire la risposta nella lingua corretta, se disponibile.'
        - schema:
            type: string
          in: header
          name: Origin
          description: 'Utilizzato in contesti di sicurezza per indicare l''origine della richiesta, ad esempio durante le richieste CORS (Cross-Origin Resource Sharing).'
        - schema:
            type: string
          in: header
          name: User-Agent
          description: 'Utilizzato per identificare il client che sta effettuando la richiesta, ad esempio il browser e la versione utilizzata.'
components:
  schemas:
    StudentiAnnoCorso:
      type: object
      x-examples:
        Example 1:
          instituteName: Università degli Studi di Milano
          courseType: Laurea
          courseName: Ingegneria
          classCode: LM-23
          className: Civile e Ambientale
          registeredPerYear:
            firstYear: 50
            secondYear: 40
            thirdYear: 30
      description: Numero di studenti per anno di un corso di studi
      properties:
        instituteName:
          type: string
          description: Nome dell'istituto
          readOnly: true
        courseType:
          type: string
          description: Tipo di corso di studio
          example: 'laurea, laurea magistrale, dottorato di ricerca, specializzazione, master, formazione professionale'
          readOnly: true
        courseName:
          type: string
          description: Denominazione del corso di studio
          example: 'ingegneria, economia, giurisprudenza, medicina, scienze umanistiche, scienze sociali, informatica, arte e design'
          readOnly: true
        classCode:
          type: string
          description: Codice della classe di studio
          pattern: '^[A-Za-z0-9-]+$'
          example: L-8
          readOnly: true
        className:
          type: string
          description: Denominazione della classe di studio
          example: 'Informatica, Meccanica, Elettronica, Civile'
          readOnly: true
        registeredPerYear:
          type: object
          description: Numero studenti iscritti al corso raggruppati per anno
          properties:
            firstYear:
              type: integer
              format: int32
              readOnly: true
            secondYear:
              type: integer
              format: int32
              readOnly: true
            thirdYear:
              type: integer
              format: int32
              readOnly: true
  requestBodies: {}
  responses: {}
servers:
  - url: 'https://localhost:8080/api'
    description: localhost
tags:
  - name: API-ANIS
  - name: HEALTH-CHECK
  - name: STUDENTI-ANNO-CORSO
