openapi: 3.0.0
x-stoplight:
  id: 0f56e32f16f60
info:
  title: API riferimento ANIS
  x-summary: Questo servizio ritorna l'elenco degli studenti che hanno conseguito il titolo con una determinata votazione minima.
  version: 1.0.0
  description: |
    ### Documentazione

    ## API riferimento ANIS
    La seguente documentazione API fornisce un riferimento per l'integrazione e 
    l'accesso ai dati ANIS (ANagrafe degli Studenti) relativi alle università. 
    Queste API consentono l'erogazione di servizi (e-service) che operano sui dati ANIS.

    # API Health Check
    Questa API fornisce un modo semplice per verificare lo stato di salute del sistema. 
    È un endpoint di base che può essere utilizzato per controllare se il servizio è in esecuzione correttamente.

    **Endpoint:**    GET  /status


    # Studenti che hanno conseguito il titolo con votazione maggiore di x
    Questa API consente di ottenere il numero di studenti che hanno conseguito un titolo con votazione maggiore di un determinato valore. Restituisce i dati relativi al corso e il conteggio degli studenti che soddisfano il criterio di avere una votazione superiore a quella inserita per il titolo conseguito.

    **Endpoint:**   GET  /titoli/{titleName}/voto-maggiore/{vote}

    **Params:**    
          - `{titleName}` : Nome specifico del titolo di studio conseguito, 
          - `{vote}`: Rappresenta il valore minimo di votazione per il titolo conseguito. 

    **Esempio di risposta:**

    ```json
    {
      "instituteName": "Università degli Studi di Roma 'La Sapienza' ",
      "titleName": "Laurea Magistrale in Ingegneria Informatica",
      "courseType": "Laurea Magistrale",
      "referenceVote": "95/110",
      "numberOfStudents": 150
    }
  contact:
    name: helpdesk
    email: helpdesk@gmail.com
  x-api-id: 00000000-0000-0000-0000-000000000000
  termsOfService: 'http://swagger.io/terms/'
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
paths:
  /status:
    get:
      summary: Health Check
      operationId: check-status
      description: Verificare lo stato di salute del sistema
      tags:
        - HEALTH-CHECK
      responses:
        '204':
          description: il servizio è in esecuzione correttamente.
        '500':
          description: il servizio non è in esecuzione.
  '/titoli/{titleName}/voto-maggiore/{vote}':
    parameters:
      - schema:
          type: string
        name: vote
        in: path
        required: true
        description: valore minimo di votazione per il titolo conseguito.
      - schema:
          type: string
        name: titleName
        in: path
        required: true
        description: nome specifico del titolo di studio conseguito
    get:
      summary: Studenti che hanno conseguito il titolo con votazione maggiore di X
      tags:
        - TITOLO-VOTO
      responses:
        '200':
          description: Richiesta eseguita con successo
          headers:
            Content-Length:
              schema:
                type: integer
                format: int64
              description: 'utilizzato per indicare la dimensione del corpo della risposta, consentendo al client di gestire correttamente la ricezione dei dati.'
            Cache-Control:
              schema:
                type: string
              description: 'utilizzato per indicare al client o ai server intermedi come gestire la memorizzazione nella cache della risposta, ad esempio "no-cache" per impedire la memorizzazione nella cache.'
            Access-Control-Allow-Origin:
              schema:
                type: string
              description: utilizzato per consentire a determinati origini di accedere alle risorse tramite richieste cross-origin.
            X-RateLimit-Limit:
              schema:
                type: integer
                format: int64
              description: specifica il numero massimo di richieste consentite entro un determinato periodo di tempo (solitamente misurato in secondi).
            X-RateLimit-Remaining:
              schema:
                type: integer
                format: int64
              description: utilizzato per indicare il numero di richieste API rimanenti all'interno del periodo di tempo specificato dal server.
            X-RateLimit-Reset:
              schema:
                type: string
                format: date-time
              description: utilizzato per indicare il momento in cui il limite delle richieste API verrà ripristinato.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StudentiTitolo'
              examples:
                Example 1:
                  value:
                    instituteName: 'Università degli Studi di Roma ''La Sapienza'' '
                    titleName: Laurea Magistrale in Ingegneria Informatica
                    courseType: Laurea Magistrale
                    referenceVote: 95/110
                    numberOfStudents: 150
        '404':
          description: Titolo non trovato
          headers:
            Content-Length:
              schema:
                type: integer
                format: int64
              description: 'utilizzato per indicare la dimensione del corpo della risposta, consentendo al client di gestire correttamente la ricezione dei dati.'
            Cache-Control:
              schema:
                type: string
              description: 'utilizzato per indicare al client o ai server intermedi come gestire la memorizzazione nella cache della risposta, ad esempio "no-cache" per impedire la memorizzazione nella cache.'
            Access-Control-Allow-Origin:
              schema:
                type: string
              description: utilizzato per consentire a determinati origini di accedere alle risorse tramite richieste cross-origin.
            X-RateLimit-Limit:
              schema:
                type: integer
                format: int64
              description: specifica il numero massimo di richieste consentite entro un determinato periodo di tempo (solitamente misurato in secondi).
            X-RateLimit-Remaining:
              schema:
                type: integer
                format: int64
              description: utilizzato per indicare il numero di richieste API rimanenti all'interno del periodo di tempo specificato dal server.
            X-RateLimit-Reset:
              schema:
                type: string
                format: date-time
              description: utilizzato per indicare il momento in cui il limite delle richieste API verrà ripristinato.
        '500':
          description: Errore interno del server
          headers:
            Content-Length:
              schema:
                type: integer
                format: int64
              description: 'utilizzato per indicare la dimensione del corpo della risposta, consentendo al client di gestire correttamente la ricezione dei dati.'
            Cache-Control:
              schema:
                type: string
              description: 'utilizzato per indicare al client o ai server intermedi come gestire la memorizzazione nella cache della risposta, ad esempio "no-cache" per impedire la memorizzazione nella cache.'
            Access-Control-Allow-Origin:
              schema:
                type: string
              description: utilizzato per consentire a determinati origini di accedere alle risorse tramite richieste cross-origin.
            X-RateLimit-Limit:
              schema:
                type: integer
                format: int64
              description: specifica il numero massimo di richieste consentite entro un determinato periodo di tempo (solitamente misurato in secondi).
            X-RateLimit-Remaining:
              schema:
                type: integer
                format: int64
              description: utilizzato per indicare il numero di richieste API rimanenti all'interno del periodo di tempo specificato dal server.
            X-RateLimit-Reset:
              schema:
                type: string
                format: date-time
              description: utilizzato per indicare il momento in cui il limite delle richieste API verrà ripristinato.
      operationId: studenti-titolo-voto-maggiore-di
      description: Restituisce il numero di studenti che hanno conseguito un titolo con votazione maggiore di quella specificata
      parameters:
        - schema:
            type: string
          in: header
          name: Method
          description: Specifica il metodo HTTP utilizzato per la richiesta.
        - schema:
            type: string
          in: header
          name: Path
          description: Specifica il percorso o l'endpoint dell'API a cui viene indirizzata la richiesta.
        - schema:
            type: string
          in: header
          name: Scheme
          description: 'Specifica lo schema o il protocollo utilizzato per la comunicazione tra il client e il server, come HTTP o HTTPS.'
        - schema:
            type: string
          in: header
          name: Accept-Encoding
          description: 'Utilizzato per indicare al server le opzioni di compressione supportate dal client, come gzip o deflate.'
        - schema:
            type: string
          in: header
          name: Accept-Language
          description: 'Utilizzato per indicare al server la lingua preferita per la risposta, in modo che possa restituire la risposta nella lingua corretta, se disponibile.'
        - schema:
            type: string
          in: header
          name: Origin
          description: 'Utilizzato in contesti di sicurezza per indicare l''origine della richiesta, ad esempio durante le richieste CORS (Cross-Origin Resource Sharing).'
        - schema:
            type: string
          in: header
          name: User-Agent
          description: 'Utilizzato per identificare il client che sta effettuando la richiesta, ad esempio il browser e la versione utilizzata.'
components:
  schemas:
    StudentiTitolo:
      type: object
      properties:
        instituteName:
          type: string
          description: Nome dell'istituto
          readOnly: true
        titleName:
          type: string
          description: Nome del titolo di studi
          readOnly: true
        courseType:
          type: string
          description: Tipo di corso di studio
          example: 'laurea, laurea magistrale, dottorato di ricerca, specializzazione, master, formazione professionale'
          readOnly: true
        referenceVote:
          type: string
          description: Valore minimo di votazione nel formato "voto_ottenuto/voto_max"
          pattern: ^(\d+)/(\d+)$
          example: 95/110
          readOnly: true
        numberOfStudents:
          type: integer
          description: Numero studenti
          format: int32
          readOnly: true
      x-examples:
        Example 1:
          instituteName: 'Università degli Studi di Roma ''La Sapienza'' '
          titleName: Laurea Magistrale in Ingegneria Informatica
          courseType: Laurea Magistrale
          referenceVote: 95/110
          numberOfStudents: 150
      description: Numero di studenti in base al titolo e al voto minimo conseguito
  requestBodies: {}
  responses: {}
servers:
  - url: 'https://localhost:8080/api'
    description: localhost
tags:
  - name: API-ANIS
  - name: HEALTH-CHECK
  - name: TITOLO-VOTO
