openapi: 3.0.0
x-stoplight:
  id: 0f56e32f16f60
info:
  title: IFS08 - Students enrolled by ISEE bands / Iscritti per fasce ISEE
  x-summary: Acquires the number of students by ISEE bands in an academic year / Acquisisce il numero di studentesse e studenti per fasce ISEE in un anno accademico
  version: 1.0.0
  description: |
   This API allows you to obtain the number of enrolled students divided by ISEE bands. / Questa API consente di ottenere il numero di studentesse e di studenti iscritti suddivisi per fasce ISEE.
  contact:
    name: helpdesk
    email: helpdesk@gmail.com
  x-api-id: 00000000-0000-0000-0000-000000000000
  termsOfService: 'http://swagger.io/terms/'
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
paths:
  /count-academic-enrollments-by-isee-ranges:
    post:
      summary: Acquisition of the number of female and male students in predefined ISEE brackets in study programs for an academic year at the Higher Education Institute. / Acquisizione del numero di studentesse e studenti per fasce ISEE prestabilite nei corsi di studio per un anno accademico nell'Istituto di formazione superiore
      tags:
        - count-academic-enrollments-by-isee-ranges
      security:
       - bearerAuth: []
      responses:
        '200':
          description: Request successfully executed / Richiesta eseguita con successo 
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/count_academic_enrollments_by_isee_ranges'
              examples:
                Example statuscode=200:
                  value:
                    tot_enrollment_count: 3000
                    ranges:
                      - range_description: 'ISEE non presentato'
                        isee_min_value: null
                        isee_max_value: null              
                        enrollment_count: 1000
                      - range_description: '<=13.000'
                        isee_min_value: 0
                        isee_max_value: 13000              
                        enrollment_count: 1000
                      - range_description: '13.001-16.000'
                        isee_min_value: 13001
                        isee_max_value: 16000              
                        enrollment_count: 1000  
                      - range_description: '40.001-45.000'
                        isee_min_value: 40001
                        isee_max_value: 45000             
                        enrollment_count: 500
                      - range_description: '60.001-70.000'
                        isee_min_value: 60001
                        isee_max_value: 70000             
                        enrollment_count: 500  
                      - range_description: '> 100.000'
                        isee_min_value: 100001
                        isee_max_value: null              
                        enrollment_count: 500
        '400':
          description: One of the input fields appears to be missing / Risulta mancante uno dei campi di input
        '404':
          description: No ISEE bands were found for the input fields / Non sono state trovate fasce ISEE relative ai campi in input
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/count_academic_enrollments_by_isee_ranges'
              examples:
                Example statuscode=404:
                  value:
                    programme_type_code: MS
                    degree_course_code: '469'
                    degree_class_code: LM-20
                    academic_year: 2023/2024
                    tot_enrollment_count: 3000
                    ranges: []
                    
             
        '500':
          description: Internal server error / Errore interno del server
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/isee_enrollment_request'
            examples:
              Example post 1:
                value:
                  academic_year: '2023/2024'
          application/xml:
            schema:
              type: object
              additionalProperties: false
              properties: {}
        description: ''
      
      operationId: Iscritti-per-isee
      description: Returns the list of ISEE bands with the number of students enrolled by band. By valuing the optional Params queries (courseName and academicYear) you can filter the results. If they are not valued, the result obtained will refer to the IFS in full. / Restituisce l'elenco di fasce ISEE con il numero di studentesse e di studenti iscritti per fascia. Valorizzando i queryParams opzionali (courseName e academicYear) è possibile filtrare i risultati. Non valorizzandoli il risultato ottenuto si riferirà all'IFS per intero.

  /status:
    get:
      summary: Verifica stato delle API (Health Check)
      operationId: check-status
      description: Check the system's health status / Verificare lo stato di salute del sistema
      tags:
        - health-check
      security: [{}]
      responses:
        '204':
          description: The service is running correctly / Il servizio è in esecuzione correttamente.
        '500':
          description: The service is not running. / Il servizio non è in esecuzione.
components:
  headers:
    Retry-After:
      description: |-
        Retry contacting the endpoint *at least* after seconds.
        See https://tools.ietf.org/html/rfc7231#section-7.1.3
      schema:
        format: int32
        maximum: 186400
        minimum: 0
        type: integer
    X-RateLimit-Limit:
      description: The number of allowed requests in the current period / Numero di richieste consentite nel periodo attuale
      schema:
        format: int32
        maximum: 1000000
        minimum: 0
        type: integer
    X-RateLimit-Remaining:
      description: The number of remaining requests in the current period / Numero di richieste rimanenti nel periodo attuale 
      schema:
        format: int32
        maximum: 1000000
        minimum: 0
        type: integer
    X-RateLimit-Reset:
      description: The number of seconds left in the current period / Numero di secondi rimanenti nel periodo attuale
      schema:
        format: int32
        maximum: 186400
        minimum: 0
        type: integer   
  schemas:
    ranges:
      type: object
      additionalProperties: false
      x-examples:
        Example 1:
          isee_min_value: 1000
          isee_max_value: 6000
          enrollment_count: 120
      properties:
        isee_min_value:
          type: integer
          description: Minimum value of the ISEE reference band / Valore minimo della fascia ISEE di riferimento 
          format: Int32
          readOnly: true
          minimum: 0
          maximum: 9999999    
          nullable: true       
        isee_max_value:
          type: integer
          format: Int32
          description: Maximum value of the ISEE reference band / Valore massimo della fascia ISEE di riferimento
          minimum: 0
          maximum: 9999999  
          readOnly: true
          nullable: true
        enrollment_count:
          type: integer
          format: int32
          description: Number of students enrolled by ISEE reference bracket / Numero di iscritti per fascia ISEE di riferimento 
          minimum: 0
          maximum: 1000000000          
          nullable: true
          readOnly: true
        range_description:
          type: string
          description: Description ISEE band / Descrizione Fascia ISEE
          example: '> 100000'
          readOnly: true
          nullable: true
          minLength: 0
          maxLength: 64            
      required:
        - isee_min_value
        - isee_max_value
        - enrollment_count
        - range_description
    count_academic_enrollments_by_isee_ranges:
      type: object
      nullable: true
      additionalProperties: false
      x-examples:
        Example 1:
          tot_enrollment_count: 1000
          ranges: 
            - isee_min_value: '1000'
            - isee_max_value: '15000'
            - enrollment_count: 1000
            - range_description: '> 100001'
      description: Students enrolled in the degree course by ISEE bracket / Iscritti al corso di laurea per fascia ISEE
      properties:
        tot_enrollment_count:
          type: integer
          format: int32
          description: Number of total subscribers / Numero di iscritti totali
          minimum: 0
          maximum: 1000000000          
          nullable: true
          readOnly: true     
        ranges:
          type: array
          maxItems: 500000
          minItems: 0
          description: List of ISEE bands / Elenco di fasce ISEE
          items:
            $ref: '#/components/schemas/ranges'
    isee_enrollment_request:
      type: object
      additionalProperties: false
      x-jsonld-type: https://w3id.org/italia/onto/Learning
      x-jsonld-context:
        LEA: https://w3id.org/italia/onto/Learning/
        academic_year: LEA:AcademicYear
      x-examples:
        Example 1:
          academic_year : 2023/2024
      x-stoplight:
        id: b40e2be27c423
      description: Request enrollment of a student's enrollment / Richiesta iscrizione di una studentessa o uno studente
      properties:
        academic_year:
          type: string
          description: Last academic year in which enrollment in the student's course is recorded / Ultimo anno accademico in cui risulta l'iscrizione al corso della studentessa o dello studente 
          example: 2022/2023
          pattern: '^\d{4}/\d{4}$'
          readOnly: true
          minLength: 9
          maxLength: 9
      required:
        - academic_year
  requestBodies: {}
  responses: {}
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: PASETO 
servers:
  - url: 'https://localhost:8080/api'
    description: localhost
tags:  
  - name: count-academic-enrollments-by-isee-ranges
  - name: health-check
