openapi: 3.0.0
x-stoplight:
  id: 0f56e32f16f60
info:
  title: IFS08 - Iscritti per fasce ISEE
  x-summary: Acquisisce il numero di studentesse e studenti per fasce ISEE in un anno accademico
  version: 1.0.0
  description: |
    Questa API consente di ottenere il numero di studentesse e di studenti iscritti suddivisi per fasce ISEE.
  contact:
    name: helpdesk
    email: helpdesk@gmail.com
  x-api-id: 00000000-0000-0000-0000-000000000000
  termsOfService: 'http://swagger.io/terms/'
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
paths:
  /count-academic-enrollments-by-isee-ranges:
    post:
      summary: Iscritti per fasce ISEE
      tags:
        - count-academic-enrollments-by-isee-ranges
      security:
       - bearerAuth: []
      responses:
        '200':
          description: Richiesta eseguita con successo
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/count_academic_enrollments_by_isee_ranges'
              examples:
                Example statuscode=200:
                  value:
                    programme_type_code: MS
                    degree_course_code: '469'
                    degree_class_code: LM-20
                    academic_year: 2023/2024
                    ranges:
                      - isee_min_value: '1'
                        isee_max_value: '5000'               
                        enrollment_count: 1000
                      - isee_min_value: '5001'
                        isee_max_value: '10000'               
                        enrollment_count: 500
                      - isee_min_value: '10001'
                        isee_max_value: '15000'               
                        enrollment_count: 500
                      
             
        '500':
          description: Errore interno del server
      
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/isee_enrollment_request'
            examples:
              Example post 1:
                value:
                  academic_year: '2023/2024'
                  degree_course_code: '465'
          application/xml:
            schema:
              type: object
              additionalProperties: false
              properties: {}
        description: ''
      
      operationId: iscritti-per-isee
      description: Restituisce l''elenco di fasce ISEE con il numero di studentesse e di studenti iscritti per fascia. Valorizzando i queryParams opzionali (courseName e academicYear) è possibile filtrare i risultati. Non valorizzandoli il risultato ottenuto si riferirà all''IFS per intero.

  /status:
    get:
      summary: Verifica stato delle API (Health Check)
      operationId: check-status
      description: Verificare lo stato di salute del sistema
      tags:
        - health-check
      security: [{}]
      responses:
        '204':
          description: il servizio è in esecuzione correttamente.
        '500':
          description: il servizio non è in esecuzione.
components:
  headers:
    Retry-After:
      description: |-
        Retry contacting the endpoint *at least* after seconds.
        See https://tools.ietf.org/html/rfc7231#section-7.1.3
      schema:
        format: int32
        maximum: 186400
        minimum: 0
        type: integer
    X-RateLimit-Limit:
      description: The number of allowed requests in the current period
      schema:
        format: int32
        maximum: 1000000
        minimum: 0
        type: integer
    X-RateLimit-Remaining:
      description: The number of remaining requests in the current period
      schema:
        format: int32
        maximum: 1000000
        minimum: 0
        type: integer
    X-RateLimit-Reset:
      description: The number of seconds left in the current period
      schema:
        format: int32
        maximum: 186400
        minimum: 0
        type: integer   
  schemas:
    ranges:
      type: object
      additionalProperties: false
      x-examples:
        Example 1:
          isee_min_value: '1000'
          isee_max_value: '6000'
          enrollment_count: 120
      properties:
        isee_min_value:
          type: string
          description: Valore minimo della fascia
          readOnly: true
          minLength: 1
          maxLength: 10           
        isee_max_value:
          type: string
          description: Valore massimo della fascia
          minLength: 1
          maxLength: 10  
          readOnly: true
        enrollment_count:
          type: integer
          format: int32
          description: Numero di iscritti per fascia
          minimum: 0
          maximum: 1000000000          
          nullable: true
          readOnly: true
      required:
        - isee_min_value
        - isee_max_value
        - enrollment_count
    count_academic_enrollments_by_isee_ranges:
      type: object
      nullable: true
      additionalProperties: false
      x-jsonld-type: https://w3id.org/italia/onto/xxx/yyy
      x-jsonld-context:
        '@vocab': http://w3id.org/italia/onto/xxx/
        programme_type_code: programme_type_code
        degree_course_code: degree_course_code
        degree_class_code: degree_class_code
      x-examples:
        Example 1:
          programme_type_code: MS
          degree_course_code: 469
          degree_class_code: LM-20
          academic_year: 2023-2024
          ranges: 
            - isee_min_value: '1000'
            - isee_max_value: '15000'
            - enrollment_count: 1000
      description: Iscritti al corso di laurea per fascia ISEE
      properties:
        programme_type_code:
          type: string
          description: Code of study program / codice del corso di studio
          example: 'LM'
          readOnly: true
          minLength: 1
          maxLength: 2
        degree_course_code:
          type: string
          description: Course code / Codice del corso
          readOnly: true
          minLength: 1
          maxLength: 20
        degree_class_code:
          type: string
          description: Identification code of the degree class / Codice identificativo della classe di laurea
          example: L-8
          readOnly: true
          minLength: 2
          maxLength: 20
        academic_year:
          type: string
          description: Last academic year in which enrollment in the student's course is recorded / Ultimo anno accademico in cui risulta l'iscrizione al corso della studentessa o dello studente 
          example: 2022/2023
          pattern: '^\d{4}/\d{4}$'
          readOnly: true
          minLength: 9
          maxLength: 9
        ranges:
          type: array
          maxItems: 500000
          minItems: 0
          description: Elenco di fasce ISEE
          items:
            $ref: '#/components/schemas/ranges'
            
    isee_enrollment_request:
      type: object
      additionalProperties: false      
      x-examples:
        Example 1:
          academic_year : 2023/2024
          degree_course_code: 456
      x-stoplight:
        id: b40e2be27c423
      description: Request enrollment of a student's enrollment / Richiesta iscrizione di una studentessa o uno studente
      properties:
        academic_year:
          type: string
          description: Last academic year in which enrollment in the student's course is recorded / Ultimo anno accademico in cui risulta l'iscrizione al corso della studentessa o dello studente 
          example: 2022/2023
          pattern: '^\d{4}/\d{4}$'
          readOnly: true
          minLength: 9
          maxLength: 9
        degree_course_code:
          type: string
          description: Course code / Codice del corso
          readOnly: true
          minLength: 1
          maxLength: 20
      required:
        - academic_year      
        - degree_course_code			        
            
            
  requestBodies: {}
  responses: {}
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: PASETO 
servers:
  - url: 'https://localhost:8080/api'
    description: localhost
tags:  
  - name: count-academic-enrollments-by-isee-ranges
  - name: health-check
