openapi: 3.0.0
info:
  title: IFS09 - Iscritti a un corso per anno
  x-summary: Acquisisce il numero di studentesse e studenti iscritti a uno specifico corso per anno accademico
  version: 1.0.0
  description: |
    Obtains the number of students enrolled in an IFS. / Ottiene il numero di studentesse e di studenti iscritti ad un IFS.
  contact:
    name: helpdesk
    email: helpdesk@gmail.com
  x-api-id: 00000000-0000-0000-0000-000000000000
  termsOfService: 'http://swagger.io/terms/'
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
paths:
  /count-accademic-enrollments-by-degree-courses:
    post:
      summary: Retrieve of the number of female and male students enrolled in a study program per academic year. / Acquisizione del numero di studentesse e studenti iscritti a un corso di studi per anno accademico
      tags:
        - IFS09.1 - count-accademic-enrollments-by-degree-courses
      security: 
        - bearerAuth: []
      responses:
        '200':
          description: Request successfully executed / Richiesta eseguita con successo
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/count_academic_enrollments_by_degree_courses'
              examples:
                Example statuscode=200:
                  value:
                    count_academic_enrollment:
                      - programme_type_code: MS
                        degree_course_code: '469'
                        degree_class_code: MSLM32
                        female_enrollment_count: 15000
                        male_enrollment_count: null                        
                      - programme_type_code: MS
                        degree_course_code: '355'
                        degree_class_code: MSLM20
                        female_enrollment_count: 10000  
                        male_enrollment_count: 5600  
                        
        '400':
          description: One of the input fields appears to be missing / Risulta mancante uno dei campi di input
        '404':
          description: No enrollments were found for the student at this institution / Non sono state trovate iscrizioni per la studentessa o lo studente in questo istituto
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/count_academic_enrollments_by_degree_courses'
              examples:
                Example statuscode=404:
                  value:
                    count_academic_enrollment: []

        '500':
          description: Internal server error / Errore interno del server 
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/count_enrollment_request'
            examples:
              Example post 1:
                value:
                  academic_year: '2023/2024'
              Example post 2:
                value:
                  academic_year: '2023/2024'
                  degree_course_code: '465'    
          application/xml:
            schema:
              type: object
              additionalProperties: false
              properties: {}
        description: ''
      operationId: iscritti-per-isee
      description: 'Restituisce il numero di studentesse e di studenti iscritti. Valorizzando i queryParams opzionali (courseName e academicYear) è possibile filtrare i risultati. Non valorizzandoli il risultato ottenuto si riferirà all''IFS per intero.'

  /status:
    get:
      summary: Verifica stato delle API (Health Check)
      operationId: check-status
      description: Check the system's health status / Verificare lo stato di salute del sistema
      tags:
        - health-check
      security: [{}]       
      responses:
        '204':
          description: The service is running correctly / il servizio è in esecuzione correttamente.
        '500':
          description: The service is not running. / il servizio non è in esecuzione.
components:
  headers:
    Retry-After:
      description: |-
        Retry contacting the endpoint *at least* after seconds.
        See https://tools.ietf.org/html/rfc7231#section-7.1.3
      schema:
        format: int32
        maximum: 186400
        minimum: 0
        type: integer
    X-RateLimit-Limit:
      description: The number of allowed requests in the current period / Numero di richieste consentite nel periodo attuale
      schema:
        format: int32
        maximum: 1000000
        minimum: 0
        type: integer
    X-RateLimit-Remaining:
      description: The number of remaining requests in the current period / Numero di richieste rimanenti nel periodo attuale 
      schema:
        format: int32
        maximum: 1000000
        minimum: 0
        type: integer
    X-RateLimit-Reset:
      description: The number of seconds left in the current period / Numero di secondi rimanenti nel periodo attuale
      schema:
        format: int32
        maximum: 186400
        minimum: 0
        type: integer  
  schemas:
    count_academic_enrollments_by_degree_courses:
      additionalProperties: false
      type: object            
      description: Enrollment details of student / Dettaglio iscrizioni di una studentessa o di uno studente
      properties:       
        count_academic_enrollment:
          type: array
          maxItems: 256
          minItems: 0
          description: count academic student enrollments / numero iscrizioni per corso
          items:
            $ref: '#/components/schemas/count_academic_enrollment'



    count_academic_enrollment:
      type: object
      additionalProperties: false      
      description: Detailed examination information / Informazioni dettagliate sul corso
      properties:
        programme_type_code:
          type: string
          description: Code of study program / codice del corso di studio
          example: 'LM'          
          minLength: 1
          maxLength: 2
        degree_course_code:
          type: string
          description: Course code / Codice del corso          
          minLength: 1
          maxLength: 20
        degree_class_code:
          type: string
          description: Identification code of the degree class / Codice identificativo della classe di laurea
          example: MSLM32          
          minLength: 1
          maxLength: 20
        female_enrollment_count:
          type: integer
          format: int32
          description: number of enrollment/numero di iscritti (female)
          example: 30000
          nullable: true          
          minimum: 1
          maximum: 9999999
        male_enrollment_count:
          type: integer
          format: int32
          description: number of enrollment/numero di iscritti (male)
          example: 30000
          nullable: true          
          minimum: 1
          maximum: 9999999  
      required:
        - programme_type_code
        - degree_course_code
        - degree_class_code
        - female_enrollment_count
        - male_enrollment_count        
    count_enrollment_request:
      type: object
      additionalProperties: false      
      description: Request enrollment of a student's enrollment / Richiesta iscrizione di una studentessa o uno studente
      properties:
        academic_year:
          type: string
          description: Last academic year in which enrollment in the student's course is recorded / Ultimo anno accademico in cui risulta l'iscrizione al corso della studentessa o dello studente 
          example: 2022/2023
          pattern: '^\d{4}/\d{4}$'
          minLength: 9
          maxLength: 9
        degree_course_code:
          type: string
          description: Course code / Codice del corso
          minLength: 1
          maxLength: 20
      required:
        - academic_year      
  requestBodies: {}
  responses: {}
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: PASETO 
servers:
  - url: 'https://localhost:8080/api'
    description: localhost        
tags:
  - name: IFS09.1 - count-accademic-enrollments-by-degree-courses
  - name: health-check